In [1]:
import numpy as np

In [2]:
arr = np.array(range(12)).reshape(4,3)

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
for i in np.nditer(arr):
    
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for i in arr:
    
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [8]:
for i in arr:
    
    for j in i:
    
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


## Pandas

In [9]:
import pandas as pd

In [10]:
pd.__version__

'2.0.3'

In [11]:
series1 = pd.Series([10,20,30,40])

series1

0    10
1    20
2    30
3    40
dtype: int64

In [12]:
# display dimension

series1.ndim

1

In [13]:
# shape

series1.shape

(4,)

In [15]:
# no. of ele

series1.size

4

In [16]:
# type of data structure

type(series1)

pandas.core.series.Series

In [18]:
# datatype of series elements

series1.dtypes

dtype('int64')

In [19]:
tup = ('Uwaish','Husain','Aisha','Rehman')

ser2 = pd.Series(tup)

ser2

0    Uwaish
1    Husain
2     Aisha
3    Rehman
dtype: object

In [20]:
s1 = {10.5,4,3,5}

ser3 = {s1}

ser3   # set are un-ordered

TypeError: unhashable type: 'set'

In [21]:
di = {101:'Uwaish',102:'Faiz',103:'Rehman',104:'Talib'}

ser4 = pd.Series(di)

ser4   # keys will be acting as indexes

101    Uwaish
102      Faiz
103    Rehman
104     Talib
dtype: object

In [22]:
arr = np.array(range(10,20))

ser5 = pd.Series(arr)

ser5

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int32