# Week 5, Day 21: Introduction to NumPy

**Date:** 29-7-2025
**Topic:** NumPy Array Creation and Accessing Elements

## 1. Introduction to NumPy

NumPy, which stands for **Numerical Python**, is a fundamental package for numerical computing in Python. It provides a powerful N-dimensional array object and tools for working with these arrays.

### Why NumPy?

*   **Performance:** NumPy arrays are stored in a continuous block of memory, making them more compact and faster than traditional Python lists.
*   **Functionality:** It provides a large collection of high-level mathematical functions to operate on these arrays.
*   **Data Science:** NumPy is the foundation of the data science ecosystem in Python, with libraries like Pandas, Matplotlib, and Scikit-learn built on top of it.

### NumPy Array: The Core Data Structure

The core of NumPy is the `ndarray` (N-dimensional array), which is a grid of values, all of the same type.

*   **Homogeneous:** All elements in a NumPy array must be of the same data type.
*   **Dimensions (Axes):** Arrays can have multiple dimensions.
    *   **1D Array:** A single row of elements (like a vector). Represented as `[]`.
    *   **2D Array:** A table of elements with rows and columns (like a matrix). Represented as `[[]]`.
    *   **3D Array:** A collection of 2D arrays (like a cube). Represented as `[[[]]]`.

## 2. Creating NumPy Arrays

There are several ways to create NumPy arrays, either manually from lists or dynamically using built-in functions.

In [1]:
import numpy as np

### Manual Creation using `np.array()`

You can create arrays from Python lists or tuples. The `ndim` attribute tells us the number of dimensions.

In [2]:
# 1D Array
arr1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr1d}")
print(f"Dimensions: {arr1d.ndim}")

1D Array: [1 2 3 4 5]
Dimensions: 1


In [3]:
# 2D Array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr2d}")
print(f"Dimensions: {arr2d.ndim}")

2D Array:
[[1 2 3]
 [4 5 6]]
Dimensions: 2


In [4]:
# 3D Array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Array:\n{arr3d}")
print(f"Dimensions: {arr3d.ndim}")

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3


### Dynamic Creation using NumPy Functions

NumPy provides several functions to create arrays with initial placeholders or sequences. The `.shape` attribute returns a tuple with the size of each dimension, and `.size` returns the total number of elements.

| Function | Description | Example |
| :--- | :--- | :--- |
| `np.arange()` | Create an array with a range of values (`start`, `stop`, `step`). | `np.arange(0, 10, 2)` |
| `np.linspace()` | Create an array with a specific `num` of evenly spaced values between `start` and `stop`. | `np.linspace(0, 10, 5)` |
| `np.ones()` | Create an array of a given shape, filled with `1`s. | `np.ones((2, 3))` |
| `np.zeros()` | Create an array of a given shape, filled with `0`s. | `np.zeros((2, 3))` |
| `np.identity()` | Create a square identity matrix (1s on the diagonal, 0s elsewhere). | `np.identity(3)` |
| `np.random.randint()`| Create an array of a given `size` with random integers up to a max value. | `np.random.randint(0, 10, size=(2, 3))` |

In [5]:
# np.arange(start, stop, step)
arr_arange = np.arange(10, 100, 10)
arr_arange

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
# We can use .reshape() to change the dimensions of an array
arr_reshaped = np.arange(1, 13).reshape(3, 4)
arr_reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
# np.linspace(start, stop, num_of_elements)
arr_linspace = np.linspace(2, 100, 15)
arr_linspace

array([  2.   ,   9.   ,  16.   ,  23.   ,  30.   ,  37.   ,  44.   ,  51.   ,
        58.   ,  65.   ,  72.   ,  79.   ,  86.   ,  93.   , 100.   ])

In [8]:
# np.ones(shape)
arr_ones = np.ones((2, 3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# np.zeros(shape)
arr_zeros = np.zeros((3, 4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# np.identity(n) creates an n x n identity matrix
arr_identity = np.identity(4)
arr_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# np.random.randint(max_val, size=shape)
arr_rand = np.random.randint(100, size=(2, 3))
arr_rand

array([[66, 94, 28],
       [62, 69,  7]])

## 3. Accessing and Slicing Arrays

Accessing parts of arrays is a critical skill. We use indexing to get single elements and slicing to get sub-arrays.

| Dimension | Shape | Indexing | Slicing |
| :--- | :--- | :--- | :--- |
| 1D | `(R,)` | `arr[R]` | `arr[start:stop]` |
| 2D | `(R, C)` | `arr[R, C]` | `arr[R_slice, C_slice]` |
| 3D | `(L, R, C)`| `arr[L, R, C]`| `arr[L_slice, R_slice, C_slice]`|

Where `R` is Row, `C` is Column, and `L` is Layer.

### Visualizing Array Access

```mermaid
graph TD
    subgraph "2D Array Slicing"
        direction LR
        A[arr all rows all cols] --> B{Full Array}
        C[arr row all cols] --> D{Specific Row}
        E[arr all rows column] --> F{Specific Column}
        G[arr row_start to row_end col_start to col_end] --> H{Sub-array}
    end
```

### Slicing Examples

In [12]:
arr1d = np.array(range(10, 50, 2))
arr1d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [13]:
# First element
arr1d[0]

10

In [14]:
# Last two elements
arr1d[-2:]

array([46, 48])

In [15]:
arr2d = np.array(range(1, 13)).reshape(4, 3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
# Display first column. The colon `:` means we select all rows.
arr2d[:, 0]

array([ 1,  4,  7, 10])

In [17]:
# Display the last two rows and the last two columns
# Rows from index 2 to the end, columns from index 1 to the end
arr2d[2:, 1:]

array([[ 8,  9],
       [11, 12]])

### Flipping Arrays

You can easily reverse the order of elements along a specific axis by using the `::-1` slicing syntax.

In [18]:
arr_to_flip = np.array(range(1,10), dtype=float).reshape(3,3)
arr_to_flip

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
# Flip rows (upside down)
arr_to_flip[::-1]

array([[7., 8., 9.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [20]:
# Flip columns (left to right)
arr_to_flip[:, ::-1]

array([[3., 2., 1.],
       [6., 5., 4.],
       [9., 8., 7.]])

In [21]:
# Flip both rows and columns
arr_to_flip[::-1, ::-1]

array([[9., 8., 7.],
       [6., 5., 4.],
       [3., 2., 1.]])

## 4. Hands-on Exercises

### Exercise 1: 2D Array Manipulation

**Tasks:**
1.  Create a 2D array of shape (3,3).
2.  Display the last row.
3.  Display the first column.
4.  Display the middle element (50.5).
5.  Display the first two rows and first two columns.

In [22]:
# 1. Create a 2d array of shape(3,3)
arr2d_ex = np.linspace(1, 100, 9).reshape(3, 3)
arr2d_ex

array([[  1.   ,  13.375,  25.75 ],
       [ 38.125,  50.5  ,  62.875],
       [ 75.25 ,  87.625, 100.   ]])

In [23]:
# 2. Display last row
arr2d_ex[-1]

array([ 75.25 ,  87.625, 100.   ])

In [24]:
# 3. Display first col
arr2d_ex[:, 0]

array([ 1.   , 38.125, 75.25 ])

In [25]:
# 4. Display the middle ele
arr2d_ex[1, 1]

50.5

In [26]:
# 5. Display first two rows and first two col
arr2d_ex[0:2, 0:2]

array([[ 1.   , 13.375],
       [38.125, 50.5  ]])

### Exercise 2: 3D Array Manipulation

**Tasks:**
1.  Create a 3d array of shape (3,4,5).
2.  Display the second layer.
3.  Display the last row of the first layer.
4.  Display the last two rows of the first layer.
5.  Display a part of your choice from the second layer.
6.  Display the first two layers only.

In [27]:
# 1. Create a 3d array of shape (3,4,5)
arr3d_ex = np.array(range(1, 61)).reshape(3, 4, 5)
arr3d_ex

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [28]:
# 2. Display the second layer (index 1)
arr3d_ex[1]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [29]:
# 3. Display the last row of the first layer
# Layer 0, last row (-1)
arr3d_ex[0, -1]

array([16, 17, 18, 19, 20])

In [30]:
# 4. Display the last two rows of first layer
# Layer 0, last two rows (-2:)
arr3d_ex[0, -2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
# 5. Display a part of your choice from the second layer
# Layer 1, rows from index 1 onwards, columns from index 2 onwards
arr3d_ex[1, 1:, 2:]

array([[28, 29, 30],
       [33, 34, 35],
       [38, 39, 40]])

In [32]:
# 6. Display first two layers only
arr3d_ex[:2]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]]])