# Week 5, Day 22: Advanced NumPy Operations
*   **Date:** 30-07-2025
*   **Objective:** To master advanced NumPy operations including array manipulation, conditional logic, and statistical functions.

This notebook consolidates concepts from `03 Numpy part-3.ipynb` and `NumpyDS_03.ipynb`, along with handwritten notes, into a single, comprehensive guide.

In [ ]:
import numpy as np

## 1. Combining Arrays

NumPy allows you to combine multiple arrays into one. This is often referred to as "stacking."

### a) Horizontal Stacking (`np.hstack`)
This function stacks arrays in sequence horizontally (column-wise). The arrays must have the same number of rows.

**Visualization:**
```
arr1 (4x3)            arr2 (4x5)                     h_arr (4x8)
[[ 0  1  2]            [[ 0  1  2  3  4]            [[ 0  1  2  0  1  2  3  4]
 [ 3  4  5]             [ 5  6  7  8  9]             [ 3  4  5  5  6  7  8  9]
 [ 6  7  8]   +         [10 11 12 13 14]   =         [ 6  7  8 10 11 12 13 14]
 [ 9 10 11]]            [15 16 17 18 19]]            [ 9 10 11 15 16 17 18 19]]
```

In [ ]:
# Create two arrays with the same number of rows (4)
arr1_h = np.array(range(12)).reshape(4, 3)
arr2_h = np.array(range(20)).reshape(4, 5)

print("arr1_h (4x3):\n", arr1_h)
print("\narr2_h (4x5):\n", arr2_h)

# Stack them horizontally
h_arr = np.hstack((arr1_h, arr2_h))
print("\nHorizontally Stacked Array (h_arr) (4x8):\n", h_arr)

### b) Vertical Stacking (`np.vstack`)
This function stacks arrays in sequence vertically (row-wise). The arrays must have the same number of columns.

**Visualization:**
```
arr1 (4x3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
    +
arr2 (4x3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
    =
v_arr (8x3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
```

In [ ]:
# Create two arrays with the same number of columns (3)
arr1_v = np.array(range(12)).reshape(4, 3)
arr2_v = np.array(range(12)).reshape(4, 3)

print("arr1_v (4x3):\n", arr1_v)
print("\narr2_v (4x3):\n", arr2_v)

# Stack them vertically
v_arr = np.vstack((arr1_v, arr2_v))
print("\nVertically Stacked Array (v_arr) (8x3):\n", v_arr)

### c) Depth Stacking (`np.dstack`)
This function stacks arrays in sequence depth-wise (along a third axis). The arrays must have the same shape (rows and columns). It creates a new dimension.

In [ ]:
# Create two arrays with the same shape (4x3)
arr1_d = np.array(range(12), dtype=float).reshape(4, 3)
arr2_d = np.ones((4, 3))

print("arr1_d (4x3):\n", arr1_d)
print("\narr2_d (4x3):\n", arr2_d)

# Stack them depth-wise
d_arr = np.dstack((arr1_d, arr2_d))
print("\nDepth Stacked Array (d_arr) shape:", d_arr.shape)
print("d_arr:\n", d_arr)

## 2. Splitting Arrays
Splitting is the reverse of stacking. You can split one array into multiple smaller ones.
> **Note:** The array can only be split into an equal number of divisions. For example, an array with 8 columns can be split into 2, 4, or 8 arrays, but not 3.

### a) Horizontal Splitting (`np.hsplit`)
Splits an array into multiple sub-arrays horizontally (column-wise).

In [ ]:
print("Original h_arr (4x8):\n", h_arr)

# Split into 2 arrays
h_split_2 = np.hsplit(h_arr, 2)
print("\nSplitting h_arr into 2 arrays:")
print("Array 1:\n", h_split_2[0])
print("Array 2:\n", h_split_2[1])

# Split into 4 arrays
h_split_4 = np.hsplit(h_arr, 4)
print("\nSplitting h_arr into 4 arrays:")
print("Array 1:\n", h_split_4[0])

### b) Vertical Splitting (`np.vsplit`)
Splits an array into multiple sub-arrays vertically (row-wise).

In [ ]:
print("Original v_arr (8x3):\n", v_arr)

# Split into 4 arrays
v_split_4 = np.vsplit(v_arr, 4)
print("\nSplitting v_arr into 4 arrays:")
print("Array 1:\n", v_split_4[0])
print("Array 2:\n", v_split_4[1])

## 3. Conditional Logic with `np.where`

The `np.where` function is a powerful tool for applying conditional logic across an entire array, similar to an if-else statement. 

**Syntax:** `np.where(condition, output_if_true, output_if_false)`

In [ ]:
oe_arr = np.array(range(20)).reshape(5,4)
print("Original Array:\n", oe_arr)

# Replace even numbers with 'even' and odd numbers with 'odd'
even_odd_arr = np.where(oe_arr % 2 == 0, 'even', 'odd')
print("\nArray with 'even' and 'odd':\n", even_odd_arr)

### Nested `np.where`

For more complex, multi-level conditions (like `if-elif-else`), you can nest `np.where` statements.

In [ ]:
# Create an array of random integers
random_arr = np.random.randint(1, 101, size=(5,4))
print("Original Random Array:\n", random_arr)

# Condition: 
# - If value < 50, keep the value.
# - If value >= 50, check if it's even or odd.
nested_where_arr = np.where(
    random_arr < 50,                     # Condition 1
    random_arr,                          # Output if True
    np.where(random_arr % 2 == 0, 'Even', 'Odd') # Nested Condition 2
)

print("\nArray after nested where:\n", nested_where_arr)

## 4. Array Manipulation

### a) Transpose (`.T` or `.transpose()`)

Swaps the rows and columns of an array.

In [ ]:
arr_t = np.array(range(12)).reshape(4,3)
print("Original Array (4x3):\n", arr_t)

transposed_arr = arr_t.T
print("\nTransposed Array (3x4):\n", transposed_arr)

### b) Flatten and Ravel

Both `flatten()` and `ravel()` convert a multi-dimensional array into a 1D array. 
- `flatten()`: Always returns a new copy of the array.
- `ravel()`: Returns a view of the original array if possible, which is more memory-efficient.

In [ ]:
arr_10d = np.array([[[[[[[[[[1,2,3,4,5]]]]]]]]]])
print("Original 10D array shape:", arr_10d.shape)
print("Original 10D array:\n", arr_10d)

flattened_arr = arr_10d.flatten()
print("\nFlattened array:\n", flattened_arr)

raveled_arr = arr_10d.ravel()
print("\nRaveled array:\n", raveled_arr)

## 5. Mathematical and Statistical Operations

NumPy provides a rich set of functions for performing mathematical and statistical analysis on arrays.

| Category | Functions |
|---|---|
| Arithmetic | `+`, `-`, `*`, `/`, `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()` |
| Dot Product | `np.dot()` |
| Statistics | `np.max()`, `np.min()`, `np.sum()`, `np.mean()`, `np.std()`, `np.var()` |

In [ ]:
stat_arr = np.linspace(1, 10, 16, dtype=int).reshape(4,4)
print("Statistical Array:\n", stat_arr)

print(f"Maximum value: {np.max(stat_arr)}")
print(f"Minimum value: {np.min(stat_arr)}")
print(f"Sum of all elements: {np.sum(stat_arr)}")
print(f"Mean of all elements: {np.mean(stat_arr):.2f}")
print(f"Standard Deviation: {np.std(stat_arr):.2f}")
print(f"Variance: {np.var(stat_arr):.2f}")

# Axis-specific operations
print(f"\nSum of the last row: {np.sum(stat_arr[-1])}")

## 6. Iterating Over Arrays (`np.nditer`)

`np.nditer()` provides an efficient, multi-dimensional iterator object to iterate over an array. This is the preferred method for iterating over NumPy arrays, as it's much faster than standard Python `for` loops for this purpose.

In [ ]:
iter_arr = np.array(range(1, 13)).reshape(4,3)
print("Array to iterate over:\n", iter_arr)

print("\nIterating and checking for Even/Odd:")
for element in np.nditer(iter_arr):
    if element % 2 == 0:
        print(f"{element} is Even")
    else:
        print(f"{element} is Odd")