In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("uncleaned_dataset.csv")

df

ID       Name     Age         City Product   Price  Quantity  \
0       1.0        Bob      19     New York   Shoes  135.41       2.0   
1       2.0       Judy  twenty          NaN   Shirt  306.92       4.0   
2       3.0      Frank      47        Miami   Shirt  465.80       4.0   
3       4.0     Hannah  twenty     New York   Shoes  250.79      -1.0   
4       5.0       Judy      40                Pants   49.18       5.0   
..      ...        ...     ...          ...     ...     ...       ...   
995   996.0     Hannah     NaN  Los Angeles     Tie  166.51       2.0   
996   997.0        NaN     NaN      Chicago   Socks  370.23      -1.0   
997   998.0        NaN      20     New York   Shoes  346.86       5.0   
998   999.0        Eve      21        Miami     Bag  401.77       4.0   
999  1000.0        NaN      56                  Tie  213.10       1.0   

    Purchase Date                Email      Feedback  
0      2021-09-16    user0@example.com           NaN  
1      2021-03-17    user1@example.com       Average  
2      2022-09-28    user2@example.com          Good  
3    invalid_date    user3@example.com       Average  
4      2020-05-18    user4@example.com          Good  
..            ...                  ...           ...  
995    2020-03-21  user995@example.com  Excellent     
996    2021-07-22  user996@example.com           Bad  
997    2021-07-07  user997@example.com           NaN  
998    2020-04-15  user998@example.com           NaN  
999    2021-05-24  user999@example.com       Average  

[1000 rows x 10 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   ID             983 non-null    float64
 1   Name           914 non-null    object 
 2   Age            662 non-null    object 
 3   City           899 non-null    object 
 4   Product        904 non-null    object 
 5   Price          952 non-null    float64
 6   Quantity       844 non-null    float64
 7   Purchase Date  1000 non-null   object 
 8   Email          902 non-null    object 
 9   Feedback       656 non-null    object 
dtypes: float64(3), object(7)
memory usage: 78.3+ KB


In [4]:
df.head()

ID       Name     Age      City Product   Price  Quantity Purchase Date  \
0  1.0        Bob      19  New York   Shoes  135.41       2.0    2021-09-16   
1  2.0       Judy  twenty       NaN   Shirt  306.92       4.0    2021-03-17   
2  3.0      Frank      47     Miami   Shirt  465.80       4.0    2022-09-28   
3  4.0     Hannah  twenty  New York   Shoes  250.79      -1.0  invalid_date   
4  5.0       Judy      40             Pants   49.18       5.0    2020-05-18   

               Email Feedback  
0  user0@example.com      NaN  
1  user1@example.com  Average  
2  user2@example.com     Good  
3  user3@example.com  Average  
4  user4@example.com     Good

In [5]:
df.tail()

ID       Name  Age         City Product   Price  Quantity  \
995   996.0     Hannah  NaN  Los Angeles     Tie  166.51       2.0   
996   997.0        NaN  NaN      Chicago   Socks  370.23      -1.0   
997   998.0        NaN   20     New York   Shoes  346.86       5.0   
998   999.0        Eve   21        Miami     Bag  401.77       4.0   
999  1000.0        NaN   56                  Tie  213.10       1.0   

    Purchase Date                Email      Feedback  
995    2020-03-21  user995@example.com  Excellent     
996    2021-07-22  user996@example.com           Bad  
997    2021-07-07  user997@example.com           NaN  
998    2020-04-15  user998@example.com           NaN  
999    2021-05-24  user999@example.com       Average

In [6]:
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Product', 'Price', 'Quantity',
       'Purchase Date', 'Email', 'Feedback'],
      dtype='object')

In [7]:
df.dtypes

ID               float64
Name              object
Age               object
City              object
Product           object
Price            float64
Quantity         float64
Purchase Date     object
Email             object
Feedback          object
dtype: object

In [48]:
df.describe()

ID          Age       Price   Quantity
count  1000.000000  1000.000000  952.000000  844.00000
mean    500.500000    28.411000  250.473866    2.35782
std     288.819436    14.489722  140.939305    1.96950
min       1.000000    18.000000   10.090000   -1.00000
25%     250.750000    20.000000  126.567500    1.00000
50%     500.500000    21.000000  250.860000    3.00000
75%     750.250000    29.250000  369.795000    4.00000
max    1000.000000    70.000000  499.230000    5.00000

In [ ]:
df['ID'] = df['ID'].astype(int)
df['Age'] = df['Age'].astype(int)
df['Quantity'] = df['Quantity'].astype(int)
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'])

In [9]:
df['ID'] = df['ID'].replace('nan',0)

In [10]:
df['ID'] = df['ID'].replace(0,np.nan)

df['ID'].unique()

array([   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
         10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,
         19.,   nan,   21.,   22.,   23.,   24.,   25.,   26.,   27.,
         28.,   29.,   30.,   31.,   32.,   33.,   34.,   35.,   36.,
         37.,   38.,   39.,   40.,   41.,   42.,   43.,   44.,   45.,
         46.,   47.,   48.,   49.,   50.,   51.,   52.,   53.,   54.,
         55.,   56.,   57.,   58.,   59.,   60.,   61.,   62.,   63.,
         64.,   65.,   66.,   67.,   68.,   69.,   70.,   71.,   72.,
         73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,   81.,
         82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
         91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,
        100.,  102.,  103.,  104.,  105.,  106.,  107.,  108.,  109.,
        110.,  111.,  112.,  113.,  114.,  115.,  116.,  117.,  118.,
        119.,  120.,  121.,  122.,  123.,  124.,  126.,  128.,  129.,
        130.,  131.,

In [11]:
df['ID'].isnull().sum()

np.int64(17)

In [12]:
df['ID'] = df['ID'].interpolate()

In [13]:
df.head(20)

ID       Name     Age         City Product   Price  Quantity  \
0    1.0        Bob      19     New York   Shoes  135.41       2.0   
1    2.0       Judy  twenty          NaN   Shirt  306.92       4.0   
2    3.0      Frank      47        Miami   Shirt  465.80       4.0   
3    4.0     Hannah  twenty     New York   Shoes  250.79      -1.0   
4    5.0       Judy      40                Pants   49.18       5.0   
5    6.0      Frank     NaN       Dallas   Watch   39.74       2.0   
6    7.0      Alice  twenty      Houston     Bag  469.74       1.0   
7    8.0      Grace  twenty      Chicago   Shirt  190.84       1.0   
8    9.0        Eve     NaN                  Tie  413.59       5.0   
9   10.0      David      52      Chicago     Hat   29.92       NaN   
10  11.0        Bob     NaN                Watch  158.91       5.0   
11  12.0        NaN     NaN     New York   Socks  480.69       NaN   
12  13.0        Bob     NaN     New York   Socks  365.33       2.0   
13  14.0       Judy     NaN      Chicago   Shoes  102.84       1.0   
14  15.0      David      41       Dallas   Socks  131.89       4.0   
15  16.0       Judy      43      Chicago   Socks   97.66       2.0   
16  17.0       Judy  twenty  Los Angeles     NaN  213.44       3.0   
17  18.0       Ivan     NaN          NaN   Shoes  322.93       NaN   
18  19.0      Alice     NaN                Socks  234.77      -1.0   
19  20.0      Alice     NaN  Los Angeles   Shirt  442.58       2.0   

   Purchase Date               Email      Feedback  
0     2021-09-16   user0@example.com           NaN  
1     2021-03-17   user1@example.com       Average  
2     2022-09-28   user2@example.com          Good  
3   invalid_date   user3@example.com       Average  
4     2020-05-18   user4@example.com          Good  
5     2022-05-05   user5@example.com           NaN  
6     2021-09-26   user6@example.com          Good  
7     2021-11-22   user7@example.com           Bad  
8     2022-08-31   user8@example.com       Average  
9     2023-05-25   user9@example.com           NaN  
10    2020-10-10  user10@example.com          Good  
11    2022-08-01  user11@example.com          Good  
12    2023-09-28  user12@example.com           NaN  
13    2024-01-30  user13@example.com       Average  
14    2023-07-03  user14@example.com          Good  
15    2022-04-18                 NaN           NaN  
16    2022-03-20  user16@example.com       Average  
17    2020-04-03  user17@example.com  Excellent     
18    2022-06-26  user18@example.com          Good  
19    2023-08-15  user19@example.com          Good

In [14]:
df['ID'] = df['ID'].astype(int)

df.head()

ID       Name     Age      City Product   Price  Quantity Purchase Date  \
0   1        Bob      19  New York   Shoes  135.41       2.0    2021-09-16   
1   2       Judy  twenty       NaN   Shirt  306.92       4.0    2021-03-17   
2   3      Frank      47     Miami   Shirt  465.80       4.0    2022-09-28   
3   4     Hannah  twenty  New York   Shoes  250.79      -1.0  invalid_date   
4   5       Judy      40             Pants   49.18       5.0    2020-05-18   

               Email Feedback  
0  user0@example.com      NaN  
1  user1@example.com  Average  
2  user2@example.com     Good  
3  user3@example.com  Average  
4  user4@example.com     Good

In [15]:
df['Name'].isnull().sum()

np.int64(86)

In [16]:
df['Name'] = df['Name'].replace(np.nan,'unknown')

df['Name'].isnull().sum()

np.int64(0)

In [17]:
df[df['Name']=='unknown']

ID     Name     Age           City Product   Price  Quantity  \
11     12  unknown     NaN       New York   Socks  480.69       NaN   
61     62  unknown     NaN                    Bag  118.19       3.0   
62     63  unknown  twenty                  Shirt  368.47       NaN   
67     68  unknown     NaN       New York   Socks  290.01       4.0   
76     77  unknown     NaN       New York   Shirt  168.47       2.0   
..    ...      ...     ...            ...     ...     ...       ...   
977   978  unknown      32        Phoenix   Watch   26.60       1.0   
994   995  unknown     NaN  San Francisco   Shoes  346.02       2.0   
996   997  unknown     NaN        Chicago   Socks  370.23      -1.0   
997   998  unknown      20       New York   Shoes  346.86       5.0   
999  1000  unknown      56                    Tie  213.10       1.0   

    Purchase Date                Email      Feedback  
11     2022-08-01   user11@example.com          Good  
61     2022-04-14   user61@example.com           Bad  
62     2020-02-08   user62@example.com       Average  
67     2022-07-02   user67@example.com       Average  
76   invalid_date   user76@example.com           NaN  
..            ...                  ...           ...  
977  invalid_date  user977@example.com       Average  
994    2022-12-28  user994@example.com  Excellent     
996    2021-07-22  user996@example.com           Bad  
997    2021-07-07  user997@example.com           NaN  
999    2021-05-24  user999@example.com       Average  

[86 rows x 10 columns]

In [18]:
df.iloc[10].isnull().sum()

np.int64(1)

In [19]:
df[df['ID']==11]

ID Name  Age City Product   Price  Quantity Purchase Date  \
10  11  Bob  NaN        Watch  158.91       5.0    2020-10-10   

                 Email Feedback  
10  user10@example.com     Good

In [20]:
df[df['ID']==11].isnull().sum(axis=1)

10    1
dtype: int64

In [21]:
df['Age'].unique()

array(['19', 'twenty', '47', '40', nan, '52', '41', '43', '25', '66',
       '50', '20', '38', '70', '61', '54', '64', '33', '62', '63', '51',
       '48', '67', '36', '26', '55', '32', '59', '44', '30', '39', '60',
       '29', '68', '27', '46', '49', '69', '65', '21', '35', '22', '56',
       '31', '42', '53', '18', '28', '58', '24', '23', '37', '45', '57',
       '34'], dtype=object)

In [22]:
'34'.isdigit()

True

In [23]:
'Uwaish'.isdigit()

False

In [24]:
df[df['Age']=='twenty']

ID       Name     Age           City Product   Price  Quantity  \
1      2       Judy  twenty            NaN   Shirt  306.92       4.0   
3      4     Hannah  twenty       New York   Shoes  250.79      -1.0   
6      7      Alice  twenty        Houston     Bag  469.74       1.0   
7      8      Grace  twenty        Chicago   Shirt  190.84       1.0   
16    17       Judy  twenty    Los Angeles     NaN  213.44       3.0   
..   ...        ...     ...            ...     ...     ...       ...   
980  981        Bob  twenty            NaN     NaN  422.17       5.0   
981  982      Alice  twenty    Los Angeles   Shirt  439.61       3.0   
987  988    Charlie  twenty    Los Angeles   Pants  324.38       3.0   
990  991    Mallory  twenty  San Francisco   Shirt  163.72       3.0   
991  992      Frank  twenty    Los Angeles   Shoes   87.33       4.0   

    Purchase Date                Email Feedback  
1      2021-03-17    user1@example.com  Average  
3    invalid_date    user3@example.com  Average  
6      2021-09-26    user6@example.com     Good  
7      2021-11-22    user7@example.com      Bad  
16     2022-03-20   user16@example.com  Average  
..            ...                  ...      ...  
980    2022-12-26  user980@example.com     Good  
981    2020-06-02  user981@example.com      NaN  
987    2020-01-19  user987@example.com  Average  
990    2021-06-14  user990@example.com  Average  
991    2021-03-27  user991@example.com      Bad  

[335 rows x 10 columns]

In [25]:
df['Age'].str.isdigit()

0       True
1      False
2       True
3      False
4       True
       ...  
995      NaN
996      NaN
997     True
998     True
999     True
Name: Age, Length: 1000, dtype: object

In [26]:
df2 = df[df['Age'].str.isdigit()==False]

df2

ID       Name     Age           City Product   Price  Quantity  \
1      2       Judy  twenty            NaN   Shirt  306.92       4.0   
3      4     Hannah  twenty       New York   Shoes  250.79      -1.0   
6      7      Alice  twenty        Houston     Bag  469.74       1.0   
7      8      Grace  twenty        Chicago   Shirt  190.84       1.0   
16    17       Judy  twenty    Los Angeles     NaN  213.44       3.0   
..   ...        ...     ...            ...     ...     ...       ...   
980  981        Bob  twenty            NaN     NaN  422.17       5.0   
981  982      Alice  twenty    Los Angeles   Shirt  439.61       3.0   
987  988    Charlie  twenty    Los Angeles   Pants  324.38       3.0   
990  991    Mallory  twenty  San Francisco   Shirt  163.72       3.0   
991  992      Frank  twenty    Los Angeles   Shoes   87.33       4.0   

    Purchase Date                Email Feedback  
1      2021-03-17    user1@example.com  Average  
3    invalid_date    user3@example.com  Average  
6      2021-09-26    user6@example.com     Good  
7      2021-11-22    user7@example.com      Bad  
16     2022-03-20   user16@example.com  Average  
..            ...                  ...      ...  
980    2022-12-26  user980@example.com     Good  
981    2020-06-02  user981@example.com      NaN  
987    2020-01-19  user987@example.com  Average  
990    2021-06-14  user990@example.com  Average  
991    2021-03-27  user991@example.com      Bad  

[335 rows x 10 columns]

In [27]:
df2['Age'].unique()

array(['twenty'], dtype=object)

In [28]:
df['Age'] = df['Age'].replace('twenty',20)

df['Age'].unique()

array(['19', 20, '47', '40', nan, '52', '41', '43', '25', '66', '50',
       '20', '38', '70', '61', '54', '64', '33', '62', '63', '51', '48',
       '67', '36', '26', '55', '32', '59', '44', '30', '39', '60', '29',
       '68', '27', '46', '49', '69', '65', '21', '35', '22', '56', '31',
       '42', '53', '18', '28', '58', '24', '23', '37', '45', '57', '34'],
      dtype=object)

In [29]:
df['Age'] = df['Age'].replace(np.nan,0)

In [30]:
df['Age'].dtypes

dtype('O')

In [31]:
df['Age'] = df['Age'].astype(int)

In [32]:
df['Age'].mean()

np.float64(21.313)

In [33]:
df['Age'] = df['Age'].replace(0,21)

In [34]:
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Product', 'Price', 'Quantity',
       'Purchase Date', 'Email', 'Feedback'],
      dtype='object')

In [35]:
df['City'].unique()

array(['New York', nan, 'Miami', '   ', 'Dallas', 'Houston', 'Chicago',
       'Los Angeles', 'San Francisco', 'Phoenix'], dtype=object)

In [36]:
df['City'].value_counts()

City
                 104
New York         102
San Francisco    102
Los Angeles      102
Chicago          102
Dallas           101
Miami             98
Phoenix           97
Houston           91
Name: count, dtype: int64

In [ ]:
np.fillna('Test',limit=25)

In [38]:
df['City'] = df['City'].replace('   ',np.nan)

df['City'].unique()

array(['New York', nan, 'Miami', 'Dallas', 'Houston', 'Chicago',
       'Los Angeles', 'San Francisco', 'Phoenix'], dtype=object)

In [39]:
df['City'].isnull().sum()

np.int64(205)

In [40]:
df['City'] = df['City'].fillna('New York',limit=29)

df['City'].isnull().sum()

np.int64(176)

In [41]:
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Product', 'Price', 'Quantity',
       'Purchase Date', 'Email', 'Feedback'],
      dtype='object')

In [42]:
df['Product'].unique()

array(['Shoes', 'Shirt', 'Pants', 'Watch', 'Bag', 'Tie', 'Hat', 'Socks',
       nan], dtype=object)

In [43]:
col = ['City','Product','Feedback']

res = [df[i].unique() for i in col]

res

[array(['New York', 'Miami', 'Dallas', 'Houston', 'Chicago', 'Los Angeles',
        'San Francisco', 'Phoenix', nan], dtype=object),
 array(['Shoes', 'Shirt', 'Pants', 'Watch', 'Bag', 'Tie', 'Hat', 'Socks',
        nan], dtype=object),
 array([nan, 'Average', 'Good', 'Bad', 'Excellent   '], dtype=object)]

In [44]:
df.head()

ID       Name  Age      City Product   Price  Quantity Purchase Date  \
0   1        Bob   19  New York   Shoes  135.41       2.0    2021-09-16   
1   2       Judy   20  New York   Shirt  306.92       4.0    2021-03-17   
2   3      Frank   47     Miami   Shirt  465.80       4.0    2022-09-28   
3   4     Hannah   20  New York   Shoes  250.79      -1.0  invalid_date   
4   5       Judy   40  New York   Pants   49.18       5.0    2020-05-18   

               Email Feedback  
0  user0@example.com      NaN  
1  user1@example.com  Average  
2  user2@example.com     Good  
3  user3@example.com  Average  
4  user4@example.com     Good

In [45]:
df['Feedback'] = df['Feedback'].str.strip(' ')

In [46]:
df['Feedback'].unique()

array([nan, 'Average', 'Good', 'Bad', 'Excellent'], dtype=object)

In [47]:
df['Quantity'].unique()

array([ 2.,  4., -1.,  5.,  1., nan,  3.])