In [1]:
# importing library

import numpy as np

In [9]:
np.__version__

'1.26.0'

In [10]:
# creating array

arr = np.array([1,2,3,4])

arr

array([1, 2, 3, 4])

In [11]:
# display dimension

arr.ndim

1

In [12]:
# display shape

arr.shape

(4,)

In [13]:
# display no. of ele

arr.size

4

In [14]:
# display the structure type

type(arr)

numpy.ndarray

In [15]:
# display the data type

arr.dtype

dtype('int32')

In [16]:
arr1 = np.array((2,3,4,5))

arr1

array([2, 3, 4, 5])

In [17]:
arr2 = np.array({2,3,4,5})

arr2

array({2, 3, 4, 5}, dtype=object)

In [18]:
arr3 = np.array({'a':10,'b':20,'c':30})

arr3

array({'a': 10, 'b': 20, 'c': 30}, dtype=object)

In [19]:
arr4 = np.array(range(10))

arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr5 = np.array(range(30,40))

arr5

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [22]:
arr6 = np.array(range(10,100,5))  # (min, max, increment)

arr6

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

**WAP to create a 2D array of shape (1,5) and display the dimension and shape**

In [23]:
arr = np.array([[10,20,30,40,50]])

print("Array is:",arr)
print("The dimension of array is:",arr.ndim)
print("The shape of array is:",arr.shape)

Array is: [[10 20 30 40 50]]
The dimension of array is: 2
The shape of array is: (1, 5)


In [25]:
# using range

arr = np.array([range(5)])

arr

array([[0, 1, 2, 3, 4]])

**WAP to create a 2D array of shape (3,2) and display the dimension and shape**

In [26]:
arr = np.array([[0,2],[3,4],[6,7]])

print("The array is:",arr)
print("The no. of dimensions is:",arr.ndim)
print("The shape is:",arr.shape)

The array is: [[0 2]
 [3 4]
 [6 7]]
The no. of dimensions is: 2
The shape is: (3, 2)


In [27]:
arr

array([[0, 2],
       [3, 4],
       [6, 7]])

**WAP to create an array of shape (3,5) and display shape and dimension**

In [28]:
arr2 = np.array([[2,3,4,5,5],[0,0,0,0,0],[1,1,1,1,1]])

arr2

array([[2, 3, 4, 5, 5],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [29]:
arr2.shape

(3, 5)

In [30]:
arr2.ndim

2

**WAP to create a 3D array of shape (1,1,4) and display shape and dimension**

In [31]:
arr3d = np.array([[[10,20,30,40]]])

arr3d

array([[[10, 20, 30, 40]]])

In [32]:
arr3d.shape

(1, 1, 4)

In [33]:
arr3d.ndim

3

**WAP to create a 3d array of shape (1,3,4) and display shape and dimension**

In [34]:
arr3d = np.array([[[0,1,2,3],[6,7,8,9],[0,9,8,7]]])

arr3d

array([[[0, 1, 2, 3],
        [6, 7, 8, 9],
        [0, 9, 8, 7]]])

In [35]:
arr3d.shape

(1, 3, 4)

In [36]:
arr3d.ndim

3

**WAP to create a 3d array of shape (2,3,4) and display shape and size**

In [37]:
arr3d = np.array([[[1,2,3,4],[2,2,2,2],[3,3,3,3]],[[0,0,0,0],[1,1,1,1],[2,2,2,2]]])

arr3d

array([[[1, 2, 3, 4],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]]])

In [38]:
arr3d.shape

(2, 3, 4)

In [39]:
arr3d.ndim

3

**WAP to create a 3d array of shape (3,2,3) and display shape**

In [40]:
arr = np.array([[[0,0,0],[1,1,1]],[[2,2,2],[3,3,3]],[[4,4,4],[5,5,5]]])

arr

array([[[0, 0, 0],
        [1, 1, 1]],

       [[2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [5, 5, 5]]])

**WAP to create a 3d array of (2,2,2) and display the shape**

In [41]:
arr3 = np.array([[[0,0],[1,1]],[[0,0],[1,1]]])

arr3

array([[[0, 0],
        [1, 1]],

       [[0, 0],
        [1, 1]]])

In [42]:
arr3.shape

(2, 2, 2)

In [43]:
arr1d = np.array(range(9))
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
arr2d = arr1d.reshape(3,3)

arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
arr2d = arr1d.reshape(9,1)   # (1,9)

arr2d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [48]:
arr3d = arr1d.reshape(1,3,3)

arr3d

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [49]:
arr3d = arr1d.reshape(3,1,3)

arr3d

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [51]:
# create an array of shape (5,4) using natural numbers

arr = np.array(range(1,21)).reshape(5,4)

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

**WAP to create a 3d array of shape (2,3,4) dynamically**

In [52]:
arr3d = np.array(range(24)).reshape(2,3,4)

arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
arr3d.shape

(2, 3, 4)

In [54]:
arr1d = arr3d.reshape(24,)

arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])