In [1]:
import numpy as np

In [2]:
arr1 = np.array(range(12)).reshape(4,3)

arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
arr2 = np.array(range(20)).reshape(4,5)

arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
h_arr = np.hstack((arr1,arr2))

h_arr

array([[ 0,  1,  2,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  5,  6,  7,  8,  9],
       [ 6,  7,  8, 10, 11, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17, 18, 19]])

In [6]:
arr3 = np.array(range(18)).reshape(6,3)

arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [7]:
v_arr = np.vstack((arr1,arr3))

v_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [8]:
arr4 = np.ones((4,3))

arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
d_arr = np.dstack((arr1,arr4))

d_arr

array([[[ 0.,  1.],
        [ 1.,  1.],
        [ 2.,  1.]],

       [[ 3.,  1.],
        [ 4.,  1.],
        [ 5.,  1.]],

       [[ 6.,  1.],
        [ 7.,  1.],
        [ 8.,  1.]],

       [[ 9.,  1.],
        [10.,  1.],
        [11.,  1.]]])

In [10]:
h_arr

array([[ 0,  1,  2,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  5,  6,  7,  8,  9],
       [ 6,  7,  8, 10, 11, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17, 18, 19]])

In [13]:
np.hsplit(h_arr,2)  #(h_arr,4) (h_arr,8)

[array([[ 0,  1,  2,  0],
        [ 3,  4,  5,  5],
        [ 6,  7,  8, 10],
        [ 9, 10, 11, 15]]),
 array([[ 1,  2,  3,  4],
        [ 6,  7,  8,  9],
        [11, 12, 13, 14],
        [16, 17, 18, 19]])]

In [14]:
v_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [17]:
np.vsplit(v_arr,5)  # (v_arr,2) (v_arr,10)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [18]:
arr = np.linspace(1,15,12).reshape(4,3)

arr

array([[ 1.        ,  2.27272727,  3.54545455],
       [ 4.81818182,  6.09090909,  7.36363636],
       [ 8.63636364,  9.90909091, 11.18181818],
       [12.45454545, 13.72727273, 15.        ]])

**Array with specific datatype**

In [19]:
arr = np.linspace(1,15,12,dtype=int).reshape(4,3)

arr

array([[ 1,  2,  3],
       [ 4,  6,  7],
       [ 8,  9, 11],
       [12, 13, 15]])

In [20]:
arr = np.ones((3,3))

arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
arr.dtype

dtype('float64')

In [22]:
arr = np.ones((3,3),dtype=int)

arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
arr = np.random.randint(100,size=(5,6))

arr

array([[22, 68, 86, 11, 32, 95],
       [50, 40, 80, 86, 21, 55],
       [37, 33, 10, 26, 68, 79],
       [35, 26, 79,  2, 50, 44],
       [30, 32, 32,  6, 15, 94]])

In [25]:
np.where(arr>30,True,False)

array([[False,  True,  True, False,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [ True,  True, False, False,  True,  True],
       [ True, False,  True, False,  True,  True],
       [False,  True,  True, False, False,  True]])

In [26]:
arr2 = np.where(arr>50,'Test1','Test2')

arr2

array([['Test2', 'Test1', 'Test1', 'Test2', 'Test2', 'Test1'],
       ['Test2', 'Test2', 'Test1', 'Test1', 'Test2', 'Test1'],
       ['Test2', 'Test2', 'Test2', 'Test2', 'Test1', 'Test1'],
       ['Test2', 'Test2', 'Test1', 'Test2', 'Test2', 'Test2'],
       ['Test2', 'Test2', 'Test2', 'Test2', 'Test2', 'Test1']],
      dtype='<U5')

In [27]:
# convert all the values with which are above 50

np.where(arr>50,0,arr)

array([[22,  0,  0, 11, 32,  0],
       [50, 40,  0,  0, 21,  0],
       [37, 33, 10, 26,  0,  0],
       [35, 26,  0,  2, 50, 44],
       [30, 32, 32,  6, 15,  0]])

**WAP to create a matrix of shape (5,4) and then convert the matrix into odd and even**

In [28]:
arr = np.random.randint(100,size=(5,4))

arr

array([[94, 17, 41,  6],
       [10, 98, 86, 72],
       [88, 20, 95, 22],
       [89, 25, 26, 84],
       [79, 46, 21,  1]])

In [29]:
arr2 = np.where(arr%2==0,'Even','Odd')

arr2

array([['Even', 'Odd', 'Odd', 'Even'],
       ['Even', 'Even', 'Even', 'Even'],
       ['Even', 'Even', 'Odd', 'Even'],
       ['Odd', 'Odd', 'Even', 'Even'],
       ['Odd', 'Even', 'Odd', 'Odd']], dtype='<U4')

In [30]:
# only check when the value is above 50

np.where(arr<50,arr,np.where(arr%2==0,'Even','Odd'))

array([['Even', '17', '41', '6'],
       ['10', 'Even', 'Even', 'Even'],
       ['Even', '20', 'Odd', '22'],
       ['Odd', '25', '26', 'Even'],
       ['Odd', '46', '21', '1']], dtype='<U11')

### some more functions

In [31]:
arr = np.array(range(12)).reshape(4,3)

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
arr.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [33]:
arr.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [34]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
arr10d = np.array([[[[[[[[[[1,2,3,4,5,6,7]]]]]]]]]])

arr10d

array([[[[[[[[[[1, 2, 3, 4, 5, 6, 7]]]]]]]]]])

In [39]:
arr10d.flatten()

array([1, 2, 3, 4, 5, 6, 7])

### Operations

In [40]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
arr1*10

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [42]:
arr1/100

array([[0.  , 0.01, 0.02],
       [0.03, 0.04, 0.05],
       [0.06, 0.07, 0.08],
       [0.09, 0.1 , 0.11]])

In [45]:
arr2 = np.array(range(10,22)).reshape(4,3)

arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [46]:
arr1+arr2

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32]])

In [47]:
np.add(arr1,arr2)

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32]])

In [48]:
np.multiply(arr1,arr2)

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144],
       [171, 200, 231]])

In [50]:
arr1 = np.linspace(1,10,16).reshape(4,4)

arr1

array([[ 1. ,  1.6,  2.2,  2.8],
       [ 3.4,  4. ,  4.6,  5.2],
       [ 5.8,  6.4,  7. ,  7.6],
       [ 8.2,  8.8,  9.4, 10. ]])

In [51]:
arr2 = np.array(range(1,17)).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
np.dot(arr1,arr2)

array([[ 65.2,  72.8,  80.4,  88. ],
       [132.4, 149.6, 166.8, 184. ],
       [199.6, 226.4, 253.2, 280. ],
       [266.8, 303.2, 339.6, 376. ]])

In [53]:
np.multiply(arr1,arr2)

array([[  1. ,   3.2,   6.6,  11.2],
       [ 17. ,  24. ,  32.2,  41.6],
       [ 52.2,  64. ,  77. ,  91.2],
       [106.6, 123.2, 141. , 160. ]])

In [54]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
arr+[[100]]  #broadcasting

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [56]:
arr+[[10,11,12]] #broadcasting


array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20],
       [19, 21, 23]])

In [57]:
np.max(arr)

11

In [58]:
np.min(arr)

0

In [59]:
# display total of array
np.sum(arr)

66

In [60]:
# display the average of array
np.mean(arr)

5.5

In [61]:
# display the standard deviation of array
np.std(arr)

3.452052529534663

In [62]:
# display the variance of an array
np.var(arr)

11.916666666666666

In [63]:
# display max value in column1

np.max(arr[:,0])

9

In [64]:
# display max value is arr1

np.max(arr[0])

2

In [65]:
# display sum of last row

np.sum(arr[-1])

30

In [67]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
for var in np.nditer(arr):
    
    print(var)

0
1
2
3
4
5
6
7
8
9
10
11


In [74]:
arr3d = np.linspace(1,100,16,dtype=int).reshape(4,2,2)

arr3d

array([[[  1,   7],
        [ 14,  20]],

       [[ 27,  34],
        [ 40,  47]],

       [[ 53,  60],
        [ 67,  73]],

       [[ 80,  86],
        [ 93, 100]]])

In [75]:
for i in np.nditer(arr3d):
    
    print(i)

1
7
14
20
27
34
40
47
53
60
67
73
80
86
93
100
