In [1]:
import pandas as pd

**WAP to create a dataframe where columns are emp_id, name, role, salary**

In [3]:
di = {'emp_id':[101,102,103,104],
     'name':['Salman','Uwaish','Aisha','Sayeeda'],
     'role':['DS','AI','ML','DA'],
     'salary':[100,200,300,400]}    #dict of collection
   
print(di)
print(type(di))

{'emp_id': [101, 102, 103, 104], 'name': ['Salman', 'Uwaish', 'Aisha', 'Sayeeda'], 'role': ['DS', 'AI', 'ML', 'DA'], 'salary': [100, 200, 300, 400]}
<class 'dict'>


In [4]:
df = pd.DataFrame(di)

df

emp_id     name role  salary
0     101   Salman   DS     100
1     102   Uwaish   AI     200
2     103    Aisha   ML     300
3     104  Sayeeda   DA     400

In [5]:
df.ndim

2

In [6]:
df.shape

(4, 4)

In [7]:
df.size

16

In [8]:
df1 = pd.DataFrame({'emp_id':[101,102,103,104],
     'name':['Salman','Uwaish','Aisha','Sayeeda'],
     'role':['DS','AI','ML','DA'],
     'salary':[100,200,300,400]})  #using dict of collection
df1

emp_id     name role  salary
0     101   Salman   DS     100
1     102   Uwaish   AI     200
2     103    Aisha   ML     300
3     104  Sayeeda   DA     400

**WAP to create a dataframe using dict of array, where keys are name, course, and score**

In [9]:
import numpy as np

In [10]:
name = np.array(['Uwaish','Husain','Faiz'])
course = np.array(['DS','DA','DS'])
score = np.array([44,46,78])

di = {'Name':name,'Course':course,'Score':score}  #dict of collection
type(di)

dict

In [11]:
df2 = pd.DataFrame(di)
df2

Name Course  Score
0  Uwaish     DS     44
1  Husain     DA     46
2    Faiz     DS     78

**WAP to create a dataframe of series**

In [14]:
ser1 = pd.Series(['Uwaish','Husain','Faiz'])
ser2 = pd.Series(['DS','DA','DS'])
ser3 = pd.Series([44,46,78])

di = {'Name':ser1,'Course':ser2,'Score':ser3}  #dict of collection
type(di)

dict

In [17]:
type(ser1)

pandas.core.series.Series

In [15]:
df3 = pd.DataFrame(di)

df3

Name Course  Score
0  Uwaish     DS     44
1  Husain     DA     46
2    Faiz     DS     78

In [16]:
di = {'name':pd.Series(['Uwaish','Husain','Faiz']),
     'course':pd.Series(['DS','DA','DS']),
     'score':pd.Series([44,46,78])}

df4 = pd.DataFrame(di)

df4

name course  score
0  Uwaish     DS     44
1  Husain     DA     46
2    Faiz     DS     78

**WAP to create a dataframe of arrays where columns are: rollno,age,score**

In [21]:
arr1 = np.array(range(10,20))
arr2 = np.linspace(18,30,10,dtype=int)
arr3 = np.arange(30,40,1)

print(arr1)
print(arr2)
print(arr3)

[10 11 12 13 14 15 16 17 18 19]
[18 19 20 22 23 24 26 27 28 30]
[30 31 32 33 34 35 36 37 38 39]


In [22]:
df5 = pd.DataFrame({'roll_no':arr1,'age':arr2,'score':arr3})

df5

roll_no  age  score
0       10   18     30
1       11   19     31
2       12   20     32
3       13   22     33
4       14   23     34
5       15   24     35
6       16   26     36
7       17   27     37
8       18   28     38
9       19   30     39

**WAP to create a datframe for Osmania which has the following departments and their values resepectively** (dict of dict of list)

- Eng: Enr_Id, Student_Name, Location
- Arts: Enr_Id, Student_Name, Location
- Medical: Enr_Id, Student_Name, Location

In [23]:
Osmania = {'Eng':{'Enr_id':[1,2,3,4],
                  'Student_Name':['Uwaish','Husain','Khan','Maryam'],
                  'Location':['Hyd','Mnr','Jgt','Knr']},
          'Arts':{'Enr_id':[10,11,12,24],
                  'Student_Name':['Sayeeda','Arif','Husain','Sabeel'],
                  'Location':['Hyd','Sec','Gcl','Mhd']},
          'Medical':{'Enr_id':[21,22,23,24],
                  'Student_Name':['Anu','Salman','SRK','Kajol'],
                  'Location':['Mbi','Dli','Hyd','Blr']}}

Osmania

{'Eng': {'Enr_id': [1, 2, 3, 4],
  'Student_Name': ['Uwaish', 'Husain', 'Khan', 'Maryam'],
  'Location': ['Hyd', 'Mnr', 'Jgt', 'Knr']},
 'Arts': {'Enr_id': [10, 11, 12, 24],
  'Student_Name': ['Sayeeda', 'Arif', 'Husain', 'Sabeel'],
  'Location': ['Hyd', 'Sec', 'Gcl', 'Mhd']},
 'Medical': {'Enr_id': [21, 22, 23, 24],
  'Student_Name': ['Anu', 'Salman', 'SRK', 'Kajol'],
  'Location': ['Mbi', 'Dli', 'Hyd', 'Blr']}}

In [28]:
type(Osmania)

dict

In [25]:
# display engineering department
Osmania['Eng']

{'Enr_id': [1, 2, 3, 4],
 'Student_Name': ['Uwaish', 'Husain', 'Khan', 'Maryam'],
 'Location': ['Hyd', 'Mnr', 'Jgt', 'Knr']}

In [26]:
df = pd.DataFrame(Osmania)

df

Eng                             Arts  \
Enr_id                          [1, 2, 3, 4]                 [10, 11, 12, 24]   
Student_Name  [Uwaish, Husain, Khan, Maryam]  [Sayeeda, Arif, Husain, Sabeel]   
Location                [Hyd, Mnr, Jgt, Knr]             [Hyd, Sec, Gcl, Mhd]   

                                Medical  
Enr_id                 [21, 22, 23, 24]  
Student_Name  [Anu, Salman, SRK, Kajol]  
Location           [Mbi, Dli, Hyd, Blr]

In [27]:
eng = pd.DataFrame(Osmania['Eng'])

eng

Enr_id Student_Name Location
0       1       Uwaish      Hyd
1       2       Husain      Mnr
2       3         Khan      Jgt
3       4       Maryam      Knr

## reading a dataframe from same location

In [29]:
df = pd.read_csv('FinData.csv')

df

Segment                   Country    Product Discount Band  \
0          Government                    Canada  Carretera           NaN   
1          Government                   Germany  Carretera           NaN   
2           Midmarket                    France  Carretera           NaN   
3           Midmarket                   Germany  Carretera           NaN   
4           Midmarket                    Mexico  Carretera           NaN   
..                ...                       ...        ...           ...   
676    Small Business                    France   Amarilla          High   
677    Small Business                    Mexico   Amarilla          High   
678        Government                    Mexico    Montana          High   
679        Government                    Canada      Paseo          High   
680  Channel Partners  United States of America        VTT          High   

     Product Cost  Units Sold  Sale Price  Gross Sales  Discounts      Sales  \
0               3      1618.5          20      32370.0       0.00   32370.00   
1               3      1321.0          20      26420.0       0.00   26420.00   
2               3      2178.0          15      32670.0       0.00   32670.00   
3               3       888.0          15      13320.0       0.00   13320.00   
4               3      2470.0          15      37050.0       0.00   37050.00   
..            ...         ...         ...          ...        ...        ...   
676           260      2475.0         300     742500.0  111375.00  631125.00   
677           260       546.0         300     163800.0   24570.00  139230.00   
678             5      1368.0           7       9576.0    1436.40    8139.60   
679            10       723.0           7       5061.0     759.15    4301.85   
680           250      1806.0          12      21672.0    3250.80   18421.20   

         COGS    Profit        Date  Month Number Month Name  Year  
0     16185.0  16185.00  01-01-2023             1    January  2023  
1     13210.0  13210.00  01-01-2023             1    January  2023  
2     21780.0  10890.00  01-06-2023             6       June  2023  
3      8880.0   4440.00  01-06-2023             6       June  2023  
4     24700.0  12350.00  01-06-2023             6       June  2023  
..        ...       ...         ...           ...        ...   ...  
676  618750.0  12375.00  01-03-2023             3      March  2023  
677  136500.0   2730.00  01-10-2023            10    October  2023  
678    6840.0   1299.60  01-02-2023             2   February  2023  
679    3615.0    686.85  01-04-2023             4      April  2023  
680    5418.0  13003.20  01-05-2023             5        May  2023  

[681 rows x 16 columns]

## reading a dataframe from different location

In [30]:
df2 = pd.read_excel("C:\\Users\\uwais\\Downloads\\DA1 Score.xlsx")

df2

Name    Score
0          Ghousia Fatima  20 / 26
1       Mohd Ismail Amjad  17 / 26
2           Samreen Amjad  21 / 26
3    Mohammed Bilal Ahmed  16 / 26
4          Mohd Emroz Ali  11 / 26
5              Syed Ahmed  09 / 26
6  Mohammed Sajid Hussain  17 / 26
7         Taha Ahmad Khan  20 / 26
8         Mohammed Zubair  25 / 26
9            Rafeeq Ahmed  14 / 26

## creating custom index

In [31]:
df = pd.DataFrame({'name':['Salman','Uwaish','Aisha','Sayeeda'],
     'role':['DS','AI','ML','DA'],
     'salary':[100,200,300,400]},index=[101,102,103,104])  #using dict of collection
df

name role  salary
101   Salman   DS     100
102   Uwaish   AI     200
103    Aisha   ML     300
104  Sayeeda   DA     400

In [32]:
df = pd.DataFrame({'Age':[22,23,24,25],
                  'Score':[45,67,87,98]},index=['Uwaish','Husain','Raza','Khan'])

df

Age  Score
Uwaish   22     45
Husain   23     67
Raza     24     87
Khan     25     98