# Python for Data Analysis
## importent python libraries
1. pandas = for data analysis / manupulation
2. numpy = numaric python
3. matplotlib = ploting / visualization
4. seaborn = advanced vistulization

### Numpy: numarical python calculation

cannot use collection data-type

data structure of numpy

numpy usese data structure called array 

array = homogenius collection of data or similar data

what is the diffrence between list and aaray?
1. list: hendrogeneus, slower, stroage
2. array: homogenius , faster, caculation

#### Numpy array
1. Create: import numpy or import numpy as np
2. Uses: numpy.array() or np.array()
   - we can have any collection type daya in side np.array() example: list, tuple, set, dict, range

In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sb

In [3]:
arr = np.array([1,2,3,4,5])

print("Type of structure or class: ", type(arr))
print('Data Type: ', arr.dtype)
print('Diamension: ', arr.ndim)
print('size of aaray: ', arr.size)
print('shape of aaray: ', arr.shape) 

Type of structure or class:  <class 'numpy.ndarray'>
Data Type:  int64
Diamension:  1
size of aaray:  5
shape of aaray:  (5,)


#### Array Dimensions
1. 1D aaray = rows
2. 2D aaray = rows and colums
3. 3D aaray = 

In [4]:
# creating 1D aaray
arr2 = np.array({2,3,4,5})

arr2

array({2, 3, 4, 5}, dtype=object)

In [5]:
arr3 = np.array({'a':2, 'b':3, 'c':4, 'c':5})

arr3

array({'a': 2, 'b': 3, 'c': 5}, dtype=object)

In [6]:
arr4 = np.array(range(10))

arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr5 = np.array(range(10, 100, 5))

arr5

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [8]:
arr6 = np.array()

arr6

TypeError: array() missing required argument 'object' (pos 0)

#### 1D array 
1. rows,
2. [0,1,2,3]
3. (4,) -> number of elements

#### 2D array
1. rows, cloums
2. [[0,1,2,3]]
3. (1, 4) -> number of elements 1 = rows and 4 = colums

#### 3D array
1. rows, cloums, 
2. [[0,1,2], [2,3,4]]
3. (2, 3) -> number of elements 2 = rows and 3 = colums

> note: all 1D must be same

**WAP to Create a 2D aaray of a shape (1,5) and display the dimension and shape**

In [12]:
arr7 = np.array([[1,2,3,4,5]])

arr7.shape

(1, 5)

In [13]:
arr7.ndim

2

In [18]:
arr8 = np.array([range(5)])

arr8.shape

(1, 5)

**WAP to create a 2D aaray of shape (2,3) and display dimension**

In [23]:
arr9 =  np.array([[1,2], [2,3], [3,4]])

print("array", arr9)
print("shape: ", arr9.shape)
print("dimension", arr9.ndim)

array [[1 2]
 [2 3]
 [3 4]]
shape:  (3, 2)
dimension 2


**WAP to create a 2D aaray of shape (3, 5) and display the dimension**

In [27]:
arr10 =  np.array([[1,2,3,4,5], [2,3,4,5,6], [3,4,5,6,7]])

print("array", arr10)
print("shape: ", arr10.shape)
print("dimension", arr10.ndim)

array [[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
shape:  (3, 5)
dimension 2


#### 3D array
arr11 =  np.array([[[1,2,3,4,5]]])

(1,1,5) = 1-> layer number of 2d, 1-> row no of any 2D, 5-> colums no of 2Ds 



**WAP to Create a 3D array of shape (1,1,4) and display shape and dimension**

In [33]:
arr11 =  np.array([[[1,2,3,4]]])

print("array", arr11)
print("shape: ", arr11.shape)
print("dimension", arr11.ndim)

array [[[1 2 3 4]]]
shape:  (1, 1, 4)
dimension 3


In [43]:
# (1,3,4)
arr12 =  np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]]])

arr12

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [45]:
print("shape: ", arr12.shape)
print("dimension", arr11.ndim)

shape:  (1, 3, 4)
dimension 3


In [64]:
#(2,3,4)

arr12 =  np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]], [[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

arr12

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [65]:
print("shape: ", arr12.shape)
print("dimension", arr11.ndim)

shape:  (2, 3, 4)
dimension 3


In [67]:
arr13 = np.array([[[1],[1],[1]],[[1],[1],[1]]])
arr13

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]])

In [68]:
print("shape: ", arr13.shape)
print("dimension", arr13.ndim)

shape:  (2, 3, 1)
dimension 3


In [81]:
# (3,2,3)

arr14 = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
arr14

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [79]:
print("shape: ", arr14.shape)
print("dimension", arr14.ndim)

shape:  (3, 2, 3)
dimension 3


In [83]:
# (2,2,2)

arr15 = np.array([[[1,2], [1,2]], [[1,2], [1,2]]])

In [85]:
print("shape: ", arr15.shape)
print("dimension", arr15.ndim)

shape:  (2, 2, 2)
dimension 3


#### Dyamic array



In [89]:
arr16 = np.array([1,2,3,4,5,6,7,8,9]) 

arr_3d = arr16.reshape(1,3,3)

arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [91]:
aar17 = np.array(range(24))

arr_3d = aar17.reshape(2,3,4)

arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [111]:
arr18 = np.array(range(1,25)).reshape(2,3,4)


In [112]:
arr18.shape

(2, 3, 4)

In [113]:
arr19 = np.array(range(1,21)).reshape(5,4)
arr19

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [114]:
arr19.shape

(5, 4)