# NumPy Practice Questions

In [107]:

import numpy as np

### A. Basic Array Creation and Properties

**1. Create a 1D NumPy array of integers from 10 to 20.**

In [2]:
arr = np.array(range(10,20))

arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**2. Create a 3x3 NumPy array filled with zeros.**

In [20]:
arr = np.zeros((3,3))

arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**3. Create an array of 5 random integers between 1 and 100.**

In [21]:
arr = np.random.randint(1, 100, 5)

arr

array([22, 47, 20, 48, 48])

**4. Create a NumPy array of 10 evenly spaced numbers between 0 and 1.**

In [26]:
arr = np.linspace(0,1,10)

arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### B. Indexing and Slicing

**5. Given an array `arr = np.array([5, 10, 15, 20, 25])`, extract elements from index 1 to 3.**

In [27]:
arr = np.array([5, 10, 15, 20, 25])

In [30]:
arr[1:4]

array([10, 15, 20])

**6. From a 3x3 matrix, extract the second column.**

In [35]:
arr = np.array(range(1,10)).reshape(3,3)
print(arr)

arr[:,2:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3],
       [6],
       [9]])

**7. Replace the last element of a NumPy array with 999.**

In [36]:
arr[-1,-1] = 999

arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8, 999]])

### C. Array Operations

**8. Perform element-wise addition and multiplication on two arrays: `a = np.array([1, 2, 3])`, `b = np.array([4, 5, 6])`.**

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [38]:
mult = np.multiply(a,b)

mult

array([ 4, 10, 18])

**9. Find the mean, median, and standard deviation of the array: `arr = np.array([10, 20, 30, 40, 50])`.**

In [40]:
arr = np.array([10, 20, 30, 40, 50])

In [43]:
me = np.mean(arr)
std = np.std(arr)

print('mean', me)

print('std', std)

mean 30.0
std 14.142135623730951


**10. Create a 4x4 matrix of random integers between 1 and 50, and find the maximum value in each row.**

In [47]:
arr = np.random.randint(1, 50, 16). reshape(4,4)

mx = np.max(arr)
print(arr)
mx



[[48 33  5 29]
 [47 13 39 15]
 [30  5 33 27]
 [12 48  6 28]]


np.int64(48)

### D. Reshaping and Stacking

**11. Reshape a 1D array of 12 elements into a 3x4 matrix.**

In [49]:
arr = np.array(range(12)).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**12. Stack two arrays vertically and horizontally: `a = np.array([1, 2, 3])`, `b = np.array([4, 5, 6])`.**

In [52]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [54]:
hori = np.hstack((a,b))

hori



array([1, 2, 3, 4, 5, 6])

In [55]:
verti = np.vstack((a,b))

verti



array([[1, 2, 3],
       [4, 5, 6]])

### E. Logical Operations and Filtering

**13. Given `arr = np.array([3, 8, 12, 15, 21])`, filter out elements greater than 10.**

In [59]:
arr = np.array([3, 8, 12, 15, 21])

for i in np.nditer(arr):
    if 10 < i:
        print(i)

12
15
21


In [64]:
np.where(arr, arr>10, arr<10)

array([False, False,  True,  True,  True])

**14. Replace all odd numbers in a NumPy array with -1.**

In [94]:
arr = np.array(range(12)).reshape(3,4)

arr[arr % 2 != 0] = -1

arr

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

**15. Find the positions (indices) where the elements in the array are divisible by 3.**

In [100]:
arr = np.array(range(12)).reshape(3,4)

for i in np.nditer(arr):
    if i % 3 == 0:
        print(i, 'position')
    else:
        print(i)

0 position
1
2
3 position
4
5
6 position
7
8
9 position
10
11


In [82]:
arr = np.array(range(12)).reshape(3,4)
for i in arr:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
