# Numpy part 3

## oprations/working with arrays

1. combine:
    - Horizontal Stacking: function = np.hstack(arr1,arr2) <--> row to row 
    - Vertical Stacking function: = np.vstack(arr1,arr2)   ^| colum to colum
    - Depth Stcking: function = np.dstack(arr1,arr2) 
      - (vistuilzed example of all stacking with matrix)

In [21]:
import numpy as np

In [22]:
arr1 = np.array(range(12)).reshape(4,3)

arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
arr2 = np.array(range(20)).reshape(4,5)

arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
h_arr = np.hstack((arr1,arr2))

h_arr

array([[ 0,  1,  2,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  5,  6,  7,  8,  9],
       [ 6,  7,  8, 10, 11, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17, 18, 19]])

In [25]:
arr3 = np.array(range(12)).reshape(4,3)

arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
v_arr = np.vstack((arr1,arr3))

v_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
arr4 = np.ones((4,3))

arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
d_arr = np.dstack((arr1, arr4))

d_arr

array([[[ 0.,  1.],
        [ 1.,  1.],
        [ 2.,  1.]],

       [[ 3.,  1.],
        [ 4.,  1.],
        [ 5.,  1.]],

       [[ 6.,  1.],
        [ 7.,  1.],
        [ 8.,  1.]],

       [[ 9.,  1.],
        [10.,  1.],
        [11.,  1.]]])

# splitting of array :

1. hsplite() (array, no. of splite)
2. vsplit() (array, no. of splite)

vituilized example of splitting

example: vsplite(arr, 5)

> note: slpit can only be perfrom when its in eaqul splite 

In [33]:
np.hsplit(h_arr, 2)

[array([[ 0,  1,  2,  0],
        [ 3,  4,  5,  5],
        [ 6,  7,  8, 10],
        [ 9, 10, 11, 15]]),
 array([[ 1,  2,  3,  4],
        [ 6,  7,  8,  9],
        [11, 12, 13, 14],
        [16, 17, 18, 19]])]

In [34]:
np.vsplit(v_arr, 2)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [36]:
print(np.dsplit(d_arr, 2))

[array([[[ 0.],
        [ 1.],
        [ 2.]],

       [[ 3.],
        [ 4.],
        [ 5.]],

       [[ 6.],
        [ 7.],
        [ 8.]],

       [[ 9.],
        [10.],
        [11.]]]), array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])]


In [37]:
np.hsplit(h_arr, 4)

[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10]]),
 array([[ 2,  0],
        [ 5,  5],
        [ 8, 10],
        [11, 15]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

In [38]:
np.hsplit(h_arr, 8)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [44]:
np.vsplit(v_arr, 2)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [42]:
np.vsplit(v_arr, 4)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [43]:
np.vsplit(v_arr, 8)

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

# Array with specific datatype

In [49]:
arr = np.linspace(1,15,12,dtype=int).reshape(4,3)

arr

array([[ 1,  2,  3],
       [ 4,  6,  7],
       [ 8,  9, 11],
       [12, 13, 15]])

In [50]:
z_arr = np.ones((3,3))

z_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
z_arr.dtype

dtype('float64')

In [54]:
z_arr = np.ones((3,3),dtype=int)

z_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [55]:
z_arr.dtype

dtype('int64')

In [56]:
dir(z_arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


# np.where

np.where(condition, output if the condition id true, o/p if condition is flase)

# nested where

np.where(c1, o/p, np.where(c2, o/p, o/p))

(vistuilzed example for both)

In [59]:
np.where(arr>5, True, False)

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [60]:
np.where(arr>5, 'Test1', 'Test2')

array([['Test2', 'Test2', 'Test2'],
       ['Test2', 'Test1', 'Test1'],
       ['Test1', 'Test1', 'Test1'],
       ['Test1', 'Test1', 'Test1']], dtype='<U5')

In [61]:
np.where(arr>5, 0, arr)

array([[1, 2, 3],
       [4, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**WAP to create a matrix of shape (5,4) and then convert the matrix into odd and even**

In [64]:
oe_arr = np.array(range(20)).reshape(5,4)

np.where(oe_arr % 2 == 0, 'even', 'odd')

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']], dtype='<U4')

In [68]:
oe_arr = np.random.randint(100, size=(5,4))

np.where(oe_arr % 2 == 0, 'Even', 'Odd')

array([['Even', 'Odd', 'Odd', 'Even'],
       ['Odd', 'Even', 'Even', 'Even'],
       ['Even', 'Odd', 'Odd', 'Even'],
       ['Odd', 'Even', 'Odd', 'Odd'],
       ['Even', 'Even', 'Even', 'Even']], dtype='<U4')

In [70]:
# only check if the values is above 50
oe_arr = np.random.randint(100, size=(5,4))
np.where(oe_arr<50,oe_arr,np.where(oe_arr % 2 == 0, 'Even', 'Odd'))

array([['Odd', '28', 'Even', '23'],
       ['32', 'Even', 'Even', '37'],
       ['Odd', '49', '3', '38'],
       ['Odd', '42', '11', 'Odd'],
       ['Even', 'Even', 'Odd', '27']], dtype='<U21')

# Functions

transpose(), T -> rows to colums colums to rows
flatten(), revel() -> convert shape to 1D



In [74]:
arr = np.array(range(12)).reshape(4,3)

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [75]:
arr.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [77]:
arr.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [78]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
arr10d = np.array([[[[[[[[[[1,2,3,4,5]]]]]]]]]])

arr10d

array([[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]])

In [83]:
arr10d.flatten()

array([1, 2, 3, 4, 5])

In [84]:
arr10d.ravel()

array([1, 2, 3, 4, 5])

# Oparations

1. Arthamatic : +,-,*,/ etc.
2. mathamatical oprations: add(), multiple(), divide(), dot(), subtruct().
3. statictical: max(), min(), mean(), std(), var().

vistuized examples


In [86]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
arr1*10

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [91]:
arr2 = np.array(range(1,13)).reshape(4,3)

arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
arr1+arr2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [105]:
arr1 = np.linspace(1,10,16).reshape(4,4)

arr1

array([[ 1. ,  1.6,  2.2,  2.8],
       [ 3.4,  4. ,  4.6,  5.2],
       [ 5.8,  6.4,  7. ,  7.6],
       [ 8.2,  8.8,  9.4, 10. ]])

In [106]:
arr2 = np.array(range(1, 17)).reshape(4,4)

arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
np.dot(arr2,arr2)

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [108]:
np.multiply(arr1, arr2)

array([[  1. ,   3.2,   6.6,  11.2],
       [ 17. ,  24. ,  32.2,  41.6],
       [ 52.2,  64. ,  77. ,  91.2],
       [106.6, 123.2, 141. , 160. ]])

In [109]:
np.max(arr1)

np.float64(10.0)

In [110]:
np.min(arr1)

np.float64(1.0)

In [112]:
np.sum(arr1)

np.float64(88.0)

In [113]:
np.mean(arr1)

np.float64(5.5)

In [114]:
np.std(arr1)

np.float64(2.7658633371878665)

In [116]:
np.var(arr1)

np.float64(7.65)

In [127]:
np.max(arr[0])

np.float64(2.8)

In [128]:
np.sum(arr[-1])

np.float64(36.4)

In [129]:
arr_2d = np.array(range(1, 13)).reshape(4,3)

arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [130]:
print(np.std(arr_2d))

3.452052529534663


# np.nditer() -> n diamension itteration



In [136]:
for i in np.nditer(arr_2d):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [139]:
for i in np.nditer(arr_2d):
    if i % 2 == 0:
        print(i, 'Even')
    else:
        print(i, 'Odd')

1 Odd
2 Even
3 Odd
4 Even
5 Odd
6 Even
7 Odd
8 Even
9 Odd
10 Even
11 Odd
12 Even


In [141]:
arr3d = np.linspace(1,100,16, dtype=int).reshape(4,2,2)

arr3d

array([[[  1,   7],
        [ 14,  20]],

       [[ 27,  34],
        [ 40,  47]],

       [[ 53,  60],
        [ 67,  73]],

       [[ 80,  86],
        [ 93, 100]]])

In [ ]:
for i in np.nditer(arr3d):
    print