In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [81]:
df = pd.read_csv("Dataset/uncleaned_dataset.csv")

# It's good practice to work on a copy
df_cleaned = df.copy()

# Python Programming

**Python Basics**

### Functions Creation

```python
a = 5
```

**a** is the identifier

**=** is the operator 

**5** is the datatype

### Comprehension

**[operation for i in collection ]**

### Functions

1. lambda
2. user defined
3. map()
4. apply


### **EDA Using Python**

**important libraries**
1. Pandas
2. Numpy
3. Matplotlib
4. Seaborn

### **Section 1: Read and Understand**
1. pd.read_csv()
2. info(), describe(), head(), tail(), type(), columns

### **Section 2: Data Preprocessing**
1. Fixing Rows and Columns
   + drop()
   + rename()
   + astype()
   + to_datetime()
   + ETC

2. Fix missing values:
   + isnull()
   + fillna()
   + dropna()
   + Imputation vs Interpolation

3. Fixing Outlier
   - filter/condition
   - replace()

### Section 3: Visualization
1. matplotlib:
   + plt.figure()
   + plt.chart()
   + plt.title()
   + plt.xlable()
   + plt.ylabel()
   + plt.legend()
   + plt.show()

### section 4: Analysis
1. df['Columns'] -> univariate(), describe(), Ass(),
2. function: Aggregate(), Value_count()
3. df[['2 colums']] -> Bi variate analysis
4. Function: Groupby(), sortvalues(), reset_index(), crosstab(), set_index()
### Section 5: Additional
1. create dataframe
2. Retrieval = 1. indexing, or slicing
3. loc[] vs Iloc()
4. shape, size, ndim

column -> field -> dimension -> feation -> veriable -> 

### Feature Engineering:

columns transformation/addition



In [23]:
df.describe()

ID       Price   Quantity
count   983.000000  952.000000  844.00000
mean    501.844354  250.473866    2.35782
std     289.093592  140.939305    1.96950
min       1.000000   10.090000   -1.00000
25%     250.500000  126.567500    1.00000
50%     503.000000  250.860000    3.00000
75%     752.500000  369.795000    4.00000
max    1000.000000  499.230000    5.00000

In [24]:
df.tail()

ID       Name  Age         City Product   Price  Quantity  \
995   996.0     Hannah  NaN  Los Angeles     Tie  166.51       2.0   
996   997.0        NaN  NaN      Chicago   Socks  370.23      -1.0   
997   998.0        NaN   20     New York   Shoes  346.86       5.0   
998   999.0        Eve   21        Miami     Bag  401.77       4.0   
999  1000.0        NaN   56                  Tie  213.10       1.0   

    Purchase Date                Email      Feedback  
995    2020-03-21  user995@example.com  Excellent     
996    2021-07-22  user996@example.com           Bad  
997    2021-07-07  user997@example.com           NaN  
998    2020-04-15  user998@example.com           NaN  
999    2021-05-24  user999@example.com       Average

In [25]:
list(df.columns)

['ID',
 'Name',
 'Age',
 'City',
 'Product',
 'Price',
 'Quantity',
 'Purchase Date',
 'Email',
 'Feedback']

In [11]:
df.dtypes

ID               float64
Name              object
Age               object
City              object
Product           object
Price            float64
Quantity         float64
Purchase Date     object
Email             object
Feedback          object
dtype: object

In [12]:
df['ID'] = df['ID'].astype(int)
df['Age'] = df['Age'].astype(int)
df['Quantity'] = df['Quantity'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [27]:
df.iloc[10].isnull().sum()

np.int64(1)

In [28]:
df[df['ID']==11]

ID Name  Age City Product   Price  Quantity Purchase Date  \
10  11.0  Bob  NaN        Watch  158.91       5.0    2020-10-10   

                 Email Feedback  
10  user10@example.com     Good

In [30]:
df[df['ID']==11].isnull().sum(axis=1)

10    1
dtype: int64

In [39]:
df['Age'].unique()

array(['19', 'twenty', '47', '40', nan, '52', '41', '43', '25', '66',
       '50', '20', '38', '70', '61', '54', '64', '33', '62', '63', '51',
       '48', '67', '36', '26', '55', '32', '59', '44', '30', '39', '60',
       '29', '68', '27', '46', '49', '69', '65', '21', '35', '22', '56',
       '31', '42', '53', '18', '28', '58', '24', '23', '37', '45', '57',
       '34'], dtype=object)

In [43]:
df2 = df[df['Age'].str.isdigit()==False]

In [46]:
df2['Age'].unique()

array(['twenty'], dtype=object)

In [49]:
df2['Age'] = df2['Age'].replace('twenty', 20)

/tmp/ipykernel_36455/1560643270.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Age'] = df2['Age'].replace('twenty', 20)
/tmp/ipykernel_36455/1560643270.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Age'] = df2['Age'].replace('twenty', 20)


In [51]:
df2['Age'] = df2['Age'].replace(np.nan, 0)

/tmp/ipykernel_36455/3301544511.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Age'] = df2['Age'].replace(np.nan, 0)


In [53]:
df2['Age'].dtypes

dtype('int64')

In [55]:
df2['Age'].mean()

np.float64(20.0)

In [ ]:
df2['Age'] = df2['Age'].replace(np.nan, 0)

In [56]:
df['City'].unique()

array(['New York', nan, 'Miami', '   ', 'Dallas', 'Houston', 'Chicago',
       'Los Angeles', 'San Francisco', 'Phoenix'], dtype=object)

In [58]:
df['City'].value_counts()

City
                 104
New York         102
San Francisco    102
Los Angeles      102
Chicago          102
Dallas           101
Miami             98
Phoenix           97
Houston           91
Name: count, dtype: int64

In [61]:
df['City'] = df['City'].replace('   ', np.nan)

df['City'].unique()

array(['New York', nan, 'Miami', 'Dallas', 'Houston', 'Chicago',
       'Los Angeles', 'San Francisco', 'Phoenix'], dtype=object)

In [62]:
df['City'].isnull().sum()

np.int64(205)

In [64]:
df['City'] = df['City'].fillna('New York', limit=29)

df['City'].isnull().sum()

np.int64(147)

In [66]:
col = ['City', 'Product', 'Feedback']

res = [df[i].unique() for i in col]

res

[array(['New York', 'Miami', 'Dallas', 'Houston', 'Chicago', 'Los Angeles',
        'San Francisco', 'Phoenix', nan], dtype=object),
 array(['Shoes', 'Shirt', 'Pants', 'Watch', 'Bag', 'Tie', 'Hat', 'Socks',
        nan], dtype=object),
 array([nan, 'Average', 'Good', 'Bad', 'Excellent   '], dtype=object)]

In [67]:
df.head()

ID       Name     Age      City Product   Price  Quantity Purchase Date  \
0  1.0        Bob      19  New York   Shoes  135.41       2.0    2021-09-16   
1  2.0       Judy  twenty  New York   Shirt  306.92       4.0    2021-03-17   
2  3.0      Frank      47     Miami   Shirt  465.80       4.0    2022-09-28   
3  4.0     Hannah  twenty  New York   Shoes  250.79      -1.0  invalid_date   
4  5.0       Judy      40  New York   Pants   49.18       5.0    2020-05-18   

               Email Feedback  
0  user0@example.com      NaN  
1  user1@example.com  Average  
2  user2@example.com     Good  
3  user3@example.com  Average  
4  user4@example.com     Good

In [68]:
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Product', 'Price', 'Quantity',
       'Purchase Date', 'Email', 'Feedback'],
      dtype='object')

In [72]:
df['Feedback'].unique()

array([nan, 'Average', 'Good', 'Bad', 'Excellent   '], dtype=object)

In [79]:
df['Quantity'].unique()

df['Quantity'] = df['Quantity'].replace(np.nan, 0)

In [80]:
df['Quantity'].unique()


array([ 2.,  4., -1.,  5.,  1.,  0.,  3.])

In [71]:
df['Purchase Date'].dtypes

dtype('O')

In [82]:
df['Purchase Date'].dtypes

dtype('O')

# **1. Standardizing Column Names and Removing Duplicates**

In [83]:
# Clean column names (strip whitespace)
df_cleaned.columns = df_cleaned.columns.str.strip()

# Check for and remove duplicate rows
print(f"Number of duplicate rows: {df_cleaned.duplicated().sum()}")
df_cleaned.drop_duplicates(inplace=True)

Number of duplicate rows: 0


In [84]:
# Convert to numeric, coercing errors
df_cleaned['ID'] = pd.to_numeric(df_cleaned['ID'], errors='coerce')

# Interpolate to fill missing values and cast to integer
df_cleaned['ID'] = df_cleaned['ID'].interpolate().astype(int)

In [85]:
# Strip whitespace from names
df_cleaned['Name'] = df_cleaned['Name'].str.strip()

# Fill missing values with 'unknown'
df_cleaned['Name'].fillna('unknown', inplace=True)

/tmp/ipykernel_36455/2212193942.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['Name'].fillna('unknown', inplace=True)


In [86]:
# Replace 'twenty' with '20'
df_cleaned['Age'] = df_cleaned['Age'].replace('twenty', '20')

# Convert to a numeric type, turning non-numeric values into NaN
df_cleaned['Age'] = pd.to_numeric(df_cleaned['Age'], errors='coerce')

# Calculate the mean of the valid ages
mean_age = df_cleaned['Age'].mean()

# Fill missing values (NaNs) with the mean age and convert to integer
df_cleaned['Age'].fillna(mean_age, inplace=True)
df_cleaned['Age'] = df_cleaned['Age'].astype(int)

/tmp/ipykernel_36455/4151477618.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['Age'].fillna(mean_age, inplace=True)


In [87]:
# Strip whitespace and replace empty strings with NaN
df_cleaned['City'] = df_cleaned['City'].str.strip().replace('', np.nan)

# Find the most frequent city (mode)
city_mode = df_cleaned['City'].mode()[0]

# Fill missing values with the mode
df_cleaned['City'].fillna(city_mode, inplace=True)

/tmp/ipykernel_36455/1384675483.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['City'].fillna(city_mode, inplace=True)


In [88]:
# Fill missing Product values with the mode
product_mode = df_cleaned['Product'].mode()[0]
df_cleaned['Product'].fillna(product_mode, inplace=True)

/tmp/ipykernel_36455/145852233.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['Product'].fillna(product_mode, inplace=True)


In [89]:
# Convert to numeric, coercing errors to NaN
df_cleaned['Quantity'] = pd.to_numeric(df_cleaned['Quantity'], errors='coerce')

# Convert negative quantities to positive
df_cleaned['Quantity'] = df_cleaned['Quantity'].abs()

# Calculate the median quantity
median_quantity = df_cleaned['Quantity'].median()

# Fill missing values with the median and convert to integer
df_cleaned['Quantity'].fillna(median_quantity, inplace=True)
df_cleaned['Quantity'] = df_cleaned['Quantity'].astype(int)

/tmp/ipykernel_36455/994660288.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['Quantity'].fillna(median_quantity, inplace=True)
