## 1. Create

In [1]:
import numpy as np

In [2]:
arr1d = np.array([1,2,3,4,5])

arr1d

array([1, 2, 3, 4, 5])

In [3]:
arr1d.ndim

1

In [4]:
arr2d = np.array([[0,2,3],[2,3,4]])

arr2d

array([[0, 2, 3],
       [2, 3, 4]])

In [5]:
arr2d.ndim

2

In [6]:
arr3d = np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])

arr3d

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [7]:
arr3d.ndim

3

In [8]:
arr2d = np.array(range(9)).reshape(3,3)

arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

arange()

In [9]:
arr = np.arange(2,10,1)

arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.arange(10,100,10)

arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

**WAP to create a 2d array of shape (3,4) using arange**

In [13]:
arr2d = np.arange(1,13,1).reshape(3,4)

arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr2d.shape

(3, 4)

In [15]:
# array of shape (3,2,4)

arr3d = np.arange(1,25,1).reshape(3,2,4)

arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [16]:
arr3d.shape

(3, 2, 4)

linspace()

In [17]:
arr = np.linspace(2,20,12)  # min,max,no.of ele

arr

array([ 2.        ,  3.63636364,  5.27272727,  6.90909091,  8.54545455,
       10.18181818, 11.81818182, 13.45454545, 15.09090909, 16.72727273,
       18.36363636, 20.        ])

In [18]:
arr = np.linspace(1,10,10)

arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
# create a 2d array of shape (3,5) using linspace

arr2d = np.linspace(2,100,15).reshape(3,5)

arr2d

array([[  2.,   9.,  16.,  23.,  30.],
       [ 37.,  44.,  51.,  58.,  65.],
       [ 72.,  79.,  86.,  93., 100.]])

ones((shape))

In [20]:
arr1d = np.ones((10,))  #rows

arr1d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
arr2d = np.ones((3,4)) # rows and columns

arr2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr3d = np.ones((2,3,3))  #layer, rows, and columns

arr3d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

zeros((shape))

In [24]:
arr1d = np.zeros(3,)

arr1d

array([0., 0., 0.])

In [25]:
arr2d = np.zeros((3,4))

arr2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

identity((number))

In [27]:
arr = np.identity(4)

arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
arr = np.identity(6)

arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

np.random.randint(int,size=shape)

In [29]:
arr = np.random.randint(100,size=(3,4))

arr

array([[92,  6, 35, 91],
       [89, 60,  3, 25],
       [66, 76, 99, 72]])

In [30]:
arr1d = np.random.randint(100,size=(10,))

arr1d

array([90, 53, 39, 32,  4,  9, 98, 58, 36, 60])

## 2. Access

In [32]:
arr1d = np.array(range(10,50,2))

print(arr1d)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [33]:
# display 1st ele

arr1d[0]

10

In [34]:
# display first two el

arr1d[:2]

array([10, 12])

In [35]:
# display last two ele

arr1d[-2:]

array([46, 48])

In [36]:
arr2d = np.array(range(1,13)).reshape(4,3)

arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
# display first row

arr2d[0]

array([1, 2, 3])

In [38]:
# display last two rows

arr2d[-2:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [43]:
# display first col

arr2d[:,0]

array([ 1,  4,  7, 10])

In [42]:
# display last two col

arr2d[:,-2:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [44]:
# display first two col

arr2d[:,:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [45]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
# display last two rows and last two col (8,9 and 11,12)

arr2d[2:,1:]

array([[ 8,  9],
       [11, 12]])

**WAP to create a 2d array of shape(3,3) and perform the below tasks:**

- Display last row
- Display first col
- Display the middle ele (based on face value)
- Display first two rows and first two col

In [47]:
arr2d = np.linspace(1,100,9).reshape(3,3)

arr2d

array([[  1.   ,  13.375,  25.75 ],
       [ 38.125,  50.5  ,  62.875],
       [ 75.25 ,  87.625, 100.   ]])

In [48]:
arr2d[-1]

array([ 75.25 ,  87.625, 100.   ])

In [49]:
arr2d[:,0]

array([ 1.   , 38.125, 75.25 ])

In [51]:
arr2d[1,1]

50.5

In [52]:
arr2d[1][1]  #method2 for indexing

50.5

In [54]:
arr2d[0:2,0:2]

array([[ 1.   , 13.375],
       [38.125, 50.5  ]])

**WAP to create a 3d array of shape (3,4,5) and perform the below tasks:**

- Display the second layer
- Display the last row of first layer
- Display the last two rows of first layer
- Display a part of your choice from the second layer
- Display first two layers only

In [55]:
arr3d = np.array(range(1,61)).reshape(3,4,5)

arr3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [56]:
arr3d.shape

(3, 4, 5)

In [57]:
# display second layer

arr3d[1]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [58]:
# last row of first layer

arr3d[0,-1]

array([16, 17, 18, 19, 20])

In [59]:
# last two rows of first layer

arr3d[0,-2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [60]:
arr3d[1,1:,2:]

array([[28, 29, 30],
       [33, 34, 35],
       [38, 39, 40]])

In [61]:
arr3d[:2]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]]])

In [62]:
arr2d

array([[  1.   ,  13.375,  25.75 ],
       [ 38.125,  50.5  ,  62.875],
       [ 75.25 ,  87.625, 100.   ]])

In [64]:
# flipping rows

arr2d[::-1]

array([[ 75.25 ,  87.625, 100.   ],
       [ 38.125,  50.5  ,  62.875],
       [  1.   ,  13.375,  25.75 ]])

In [65]:
# fllipping columns

arr2d[:,::-1]

array([[ 25.75 ,  13.375,   1.   ],
       [ 62.875,  50.5  ,  38.125],
       [100.   ,  87.625,  75.25 ]])

In [66]:
# flip rows and column both

arr2d[::-1,::-1]

array([[100.   ,  87.625,  75.25 ],
       [ 62.875,  50.5  ,  38.125],
       [ 25.75 ,  13.375,   1.   ]])

In [67]:
arr3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [68]:
# flip layers

arr3d[::-1]

array([[[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [69]:
# flip rows of layer 2

arr3d[1,::-1]

array([[36, 37, 38, 39, 40],
       [31, 32, 33, 34, 35],
       [26, 27, 28, 29, 30],
       [21, 22, 23, 24, 25]])

In [70]:
arr2d = np.array([[2,3],[4,5]])

arr2d

array([[2, 3],
       [4, 5]])

In [71]:
arr2d[::-1] # rows flip

array([[4, 5],
       [2, 3]])

In [72]:
arr2d[:,::-1] # column flip

array([[3, 2],
       [5, 4]])

In [73]:
str1 = "Test"

str1[::-1]

'tseT'