# Numpy

week 5 day 21
date: 29-7-25 tuesday

numpy: it uses array as the data structure we have diffrrent Diamensions like 1D, 2D, 3D and so on

static way of making an 1D array is to use []

static way of making an 2D array is to use [[]]

static way of making an 3D array is to use [[[]]]

we can use many fuction with these arrays like

.shape

.ndim

.size

so on

---

np fuctions in numpy

1. np.array()
2. np.arange() -> mininmun maximum and incriment
3. np.linespace() -> min max
4. np.identity() -> identifing
5. np.onec
6. np.zeross

so on

In [1]:
import numpy as np

In [5]:
arr1d = np.array([1,2,3,4,5])

print(arr1d.ndim)

1


In [6]:
arr2d = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr2d.ndim)

2


In [7]:
arr3d = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])

print(arr3d.ndim)

3


In [9]:
arr = np.arange(2,100,10)

arr

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [17]:
#(3,4)

arr = np.arange(1,13,1).reshape(3,4)

arr.shape

(3, 4)

In [19]:
#(3,4, 4+)

arr = np.arange(1,49,1).reshape(3,4,4)

arr.shape

(3, 4, 4)

In [21]:
# lenspace

arr = np.linspace(2,20,12)

arr

array([ 2.        ,  3.63636364,  5.27272727,  6.90909091,  8.54545455,
       10.18181818, 11.81818182, 13.45454545, 15.09090909, 16.72727273,
       18.36363636, 20.        ])

In [23]:
# lenspace

arr = np.linspace(1,10,10)

arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

To create a 2D array of shape (3,5) using numpy.linspace, the total number of elements required is 3 * 5 = 15. The num argument in np.linspace(start, stop, num) must correspond to this total number of elements.
The provided code arr = np.linspace(1,16,1).reshape(3,5) is incorrect because np.linspace(1,16,1) creates an array with only one element, which cannot be reshaped into a (3,5) array as it requires 15 elements.

In [33]:
# create a 2D array of shape (3,5) using linespace

arr = np.linspace(1,15,15).reshape(3,5)

arr.shape

(3, 5)

In [35]:
# once 1D
    
arr = np.ones((10,))

arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
# once 2D
    
arr = np.ones((3,4))

arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
# once 3D
    
arr = np.ones((3,4,5))

arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [38]:
# zeros 1D
    
arr = np.zeros((10,))

arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
# zeros 2D
    
arr = np.zeros((3,4))

arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# zeros 3D
    
arr = np.zeros((3,4,5))

arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [37]:
# identity

arr = np.identity(4)

arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
arr = np.random.randint(100,size=(3,4))

arr

array([[66, 25, 72, 78],
       [68, 63, 14, 50],
       [39, 63, 11, 67]])

In [47]:
arr = np.random.randint(100,size=(10,))

arr

array([24, 23, 72, 29, 59, 80, 50, 97, 90, 86])

In [49]:
arr = np.random.randint(100,size=(3,4, 4))

arr

array([[[12, 56, 75, 69],
        [74, 56, 97, 78],
        [ 8, 95, 90, 30],
        [72, 85, 23, 65]],

       [[35,  1, 28, 81],
        [66, 28, 33, 77],
        [27, 72, 16, 64],
        [37,  0, 55, 56]],

       [[49, 10, 58, 66],
        [55, 19, 75, 32],
        [68,  3, 70, 74],
        [21, 13,  3, 49]]])

In [50]:
# type of random

import numpy as np
    # 1D array of 5 random floats
float_array_1d = np.random.rand(5)
print(f"1D Random Float Array:\n{float_array_1d}\n")

    # 2D array of shape (3, 4) with random floats
float_array_2d = np.random.rand(3, 4)
print(f"2D Random Float Array:\n{float_array_2d}")

1D Random Float Array:
[0.18928696 0.85104808 0.97909651 0.61727095 0.65150828]

2D Random Float Array:
[[0.35256525 0.41977599 0.7297676  0.11409165]
 [0.29932657 0.24130946 0.35201939 0.29659029]
 [0.58359685 0.11852712 0.0438898  0.67073006]]


In [51]:
import numpy as np
    # 1D array of 5 random integers between 0 and 9 (inclusive)
int_array_1d = np.random.randint(0, 10, 5)
print(f"1D Random Integer Array:\n{int_array_1d}\n")

    # 2D array of shape (3, 4) with random integers between 1 and 100 (inclusive)
int_array_2d = np.random.randint(1, 101, size=(3, 4))
print(f"2D Random Integer Array:\n{int_array_2d}")

1D Random Integer Array:
[0 6 9 6 8]

2D Random Integer Array:
[[16 32 43 53]
 [54 50 28  8]
 [37 17 97 88]]


In [52]:
import numpy as np
    # 1D array of 5 random numbers from standard normal distribution
normal_array_1d = np.random.randn(5)
print(f"1D Random Normal Array:\n{normal_array_1d}\n")

    # 2D array of shape (2, 3) with random numbers from standard normal distribution
normal_array_2d = np.random.randn(2, 3)
print(f"2D Random Normal Array:\n{normal_array_2d}")

1D Random Normal Array:
[-2.16410029 -0.82077347  0.58312446 -0.06850909  0.28677632]

2D Random Normal Array:
[[ 1.67798727 -0.02318249  0.0857317 ]
 [ 0.40859165 -0.63833515  0.57753623]]


## Acessesing 

table
      1d 2d 3d
shape [R,] [R,C] [LR,C]
indexing [R] [R, RC] [L],[L,R][L,R,C]
slicing [:] [:],[:,:] [:],[:,:],[:,:,:]

start:end, colum indexing with rows, row indexing with layer cloum indexing with L,R

In [54]:
# Acessing 1D array

arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[-1])
print(arr[-2:])
print(arr[:2])

10
50
[40 50]
[10 20]


In [70]:
# Acessing 2D array

arr = np.array([[10,20,30],[40,50,60], [70,80,90]])

arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [69]:
print(arr[0])

[10 20 30]


In [65]:
print(arr[-1])

[70 80 90]


In [66]:
print(arr[-2:])

[[40 50 60]
 [70 80 90]]


In [67]:
print(arr[:2])

[[10 20 30]
 [40 50 60]]


In [68]:
print(arr[:,-1])

[30 60 90]


In [72]:
print(arr[:,-2:])

[[20 30]
 [50 60]
 [80 90]]


In [73]:
print(arr[1:,-2:])

[[50 60]
 [80 90]]


In [74]:
print(arr[1:3,1:3])

[[50 60]
 [80 90]]


In [75]:
arr = np.array(range(10,50,2))

arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [77]:
print(arr[0])

10


In [78]:
print(arr[-2:])

[46 48]


In [79]:
print(arr[:2])

[10 12]


In [94]:
arr = np.array(range(1,13)).reshape(4,3)

arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
print(arr[:,:2])

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


In [96]:
print(arr[0])

[1 2 3]


In [99]:
print(arr[:,1:])

[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


**WAP to create a array of shape (3,3) and perform the below task**

1. display last row
2. display first colum
3. display first 2 rows and first to colums

In [100]:
arr = np.array(range(1,10)).reshape(3,3)

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
# 1. display last row

print(arr[-1])

[7 8 9]


In [102]:
# 2. display first colum

print(arr[:,0])

[1 4 7]


In [119]:
# 3. display first 2 rows and first to colums

print('\nFrist 2 rows: \n',arr[:2])
print('\nFirst 2 colums: \n',arr[:,:2])


Frist 2 rows: 
 [[1 2 3]
 [4 5 6]]

First 2 colums: 
 [[1 2]
 [4 5]
 [7 8]]


### 3D 

matrix


In [121]:
arr = np.array(range(1,19)).reshape(2,3,3)

arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [122]:
print(arr[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [123]:
print(arr[1])

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [126]:
print(arr[-1,0])

[10 11 12]


In [127]:
print(arr[0,1:3,1:3])

[[5 6]
 [8 9]]


**WAP to create a 3d array of shape (3,4,5) and perform the below tasks**
1. display the second layer
2. display the last row of the first layer
3. display the last 2 rows of first layer
4. display the part of you choice from the second layer
5. display first 2 layers only

In [128]:
arr = np.array(range(1,61)).reshape(4,3,5)

arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45]],

       [[46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [129]:
# 1. display the second layer
print(arr[1])

[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [131]:
#2. display the last row of the first layer
print(arr[0,-1])

[11 12 13 14 15]


In [132]:
#3. display the last 2 rows of first layer

print(arr[0,-2:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [133]:
#4. display the part of you choice from the second layer

print(arr[1, 1:3, 1:3])


[[22 23]
 [27 28]]


In [135]:
# 5. display first 2 layers only
print(arr[:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [139]:
arr[1]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [137]:
#c flippping rows
print(arr[1,::-1])

[[26 27 28 29 30]
 [21 22 23 24 25]
 [16 17 18 19 20]]


In [138]:
#c flippping rows
print(arr[1,:,::-1])

[[20 19 18 17 16]
 [25 24 23 22 21]
 [30 29 28 27 26]]
